### ISSUE TITLE
Crash / stall with Etcd and Kubernetes Ingress Controller with Letsencrypt

### ISSUE THREAD

**Issue by jcassee** [containous/traefik#1000]
### What version of Traefik are you using (`traefik version`)?
```
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:21:15AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?
Running on Kubernetes 1.5.1, etcd 3.0.14. Configuration:

```yml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
        name: traefik-ingress
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: containous/traefik:v1.1.2
        name: traefik-ingress
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
          - containerPort: 80
            hostPort: 80
          - containerPort: 443
            hostPort: 443
        args:
        - --etcd
        - --etcd.prefix=traefik-ingress
        - --kubernetes
      nodeSelector:
        role: edge-router
```
(Using `hostNetwork: true` because of CNI.)

Configuration from etcd:
```
/traefik-ingress/defaultEntryPoints/
/traefik-ingress/defaultEntryPoints/1=https
/traefik-ingress/defaultEntryPoints/0=http
/traefik-ingress/logLevel=DEBUG
/traefik-ingress/entryPoints/
/traefik-ingress/entryPoints/https/
/traefik-ingress/entryPoints/https/compress=true
/traefik-ingress/entryPoints/https/tls/
/traefik-ingress/entryPoints/https/address=:443
/traefik-ingress/entryPoints/http/
/traefik-ingress/entryPoints/http/address=:80
/traefik-ingress/entryPoints/http/compress=true
/traefik-ingress/entryPoints/http/redirect/
/traefik-ingress/entryPoints/http/redirect/entryPoint=https
/traefik-ingress/acme/
/traefik-ingress/acme/onHostRule=true
/traefik-ingress/acme/storage=traefik-ingress/acme/account
/traefik-ingress/acme/account/
/traefik-ingress/acme/account/object=[...]
/traefik-ingress/acme/account/lock=1ebe3bd7-f49e-4025-8c06-79574ff857fc
/traefik-ingress/acme/caServer=https://acme-staging.api.letsencrypt.org/directory
/traefik-ingress/acme/email=tech@goabout.com
/traefik-ingress/acme/entryPoint=https
/traefik-ingress/acme/onDemand=true
/traefik-ingress/leader=f2764675-35bd-4df4-8a1b-ef876b6809ac
/traefik-ingress/web/
/traefik-ingress/web/address=:8081
```

### What did you do?
I added a service:
```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-pod
    spec:
      containers:
      - name: hello-container
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    name: hello-pod
spec:
  type: ClusterIP
  selector:
    name: hello-pod
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  rules:
  - host: hello.k8s-otp-01.goabout.com
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 80
```

### What did you expect to see?
Accessing the URL `https://hello.k8s-otp-01.goabout.com`, I exected to see the Nginx welcome page.

### What did you see instead?
Sometimes, Traefik crashes:
```shell
time="2016-12-27T00:41:15Z" level=info msg="Traefik version v1.1.2 built on 2016-12-15_10:21:15AM"
time="2016-12-27T00:41:15Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":{\"EntryPoint\":\"https\",\"Regex\":\"\",\"Replacement\":\"\"},\"Auth\":null,\"Compress\":true},\"https\":{\"Network\":\"\",\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":null,\"ClientCAFiles\":null},\"Redirect\":null,\"Auth\":null,\"Compress\":true}},\"Cluster\":{\"Node\":\"0755b59b-c27f-4775-80a3-fcff9bcaf139\",\"Store\":{\"Store\":{},\"Prefix\":\"traefik-ingress\"}},\"Constraints\":[],\"ACME\":{\"Email\":\"tech@goabout.com\",\"Domains\":null,\"Storage\":\"traefik-ingress/acme/account\",\"StorageFile\":\"\",\"OnDemand\":true,\"OnHostRule\":true,\"CAServer\":\"https://acme-staging.api.letsencrypt.org/directory\",\"EntryPoint\":\"https\"},\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8081\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null},\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"127.0.0.1:2379\",\"Prefix\":\"traefik-ingress\",\"TLS\":null},\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"\",\"DisablePassHostHeaders\":false,\"Namespaces\":null,\"LabelSelector\":\"\"},\"Mesos\":null}"
time="2016-12-27T00:41:15Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc42036f440 Auth:<nil> Compress:true}"
time="2016-12-27T00:41:15Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4201c18c0 Redirect:<nil> Auth:<nil> Compress:true}"
time="2016-12-27T00:41:15Z" level=info msg="Starting server on :80"
time="2016-12-27T00:41:16Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8081\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}"
time="2016-12-27T00:41:16Z" level=info msg="Starting server on :443"
time="2016-12-27T00:41:16Z" level=debug msg="Node 0755b59b-c27f-4775-80a3-fcff9bcaf139 running for election"
time="2016-12-27T00:41:16Z" level=info msg="Starting provider *provider.Etcd {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"127.0.0.1:2379\",\"Prefix\":\"traefik-ingress\",\"TLS\":null}"
time="2016-12-27T00:41:16Z" level=info msg="Starting provider *provider.Kubernetes {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"\",\"DisablePassHostHeaders\":false,\"Namespaces\":null,\"LabelSelector\":\"\"}"
time="2016-12-27T00:41:16Z" level=info msg="Node 0755b59b-c27f-4775-80a3-fcff9bcaf139 elected slave ♝"
time="2016-12-27T00:41:16Z" level=debug msg="Kubernetes token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTJnbndyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkYzFmYzQ2ZS1jOTZmLTExZTYtOWIxMC1kNDNkN2ViZGZmYzQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.uW-pqhWYqqvmyckO8LqQ2SAUY7gMsy_k1e11SUzL79JzeYA3qsEF4TLGjufsml0Ki-YgJVhYAa96GeRR8FiB_lrrrCuv4fIKcLCHfWyZkZfiy9hSyijLBq3mreC9qvwfrvf_Fa-Wkhfse_ce7InhDtMqaO32yPPVRc18qNdmhByBk7lu5OuzywXthm9cxsq3FGSRGPEDB3loX_3VH4wsGx3wFOzYVCaCT0zASWAVo4DqgalvNYeRZj9CcdJTOowxJRMSnqxfSTK73aOqfukfzxKl3_ZIXCWkP4cw0yL8sO3od6R_Nc3rqujv1KBosbXzbQ8_0e-cYzA32zBx0rW3mA"
time="2016-12-27T00:41:16Z" level=debug msg="Kubernetes CA cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
time="2016-12-27T00:41:16Z" level=debug msg="Using environment provided kubernetes endpoint"
time="2016-12-27T00:41:16Z" level=debug msg="Kubernetes endpoint: https://10.96.0.1:443"
time="2016-12-27T00:41:16Z" level=debug msg="Datastore reload"
time="2016-12-27T00:41:16Z" level=debug msg="Using label selector: ''"
time="2016-12-27T00:41:16Z" level=debug msg="Cannot get key traefik-ingress/alias Key not found in store, setting default traefik-ingress"
time="2016-12-27T00:41:16Z" level=info msg="Node 0755b59b-c27f-4775-80a3-fcff9bcaf139 elected leader ♚"
time="2016-12-27T00:41:16Z" level=info msg="Starting ACME renew job..."
time="2016-12-27T00:41:16Z" level=debug msg="Cannot get key traefik-ingress/alias Key not found in store, setting default traefik-ingress"
time="2016-12-27T00:41:16Z" level=debug msg="Cannot get keys traefik-ingress/frontends/ Key not found in store "
time="2016-12-27T00:41:16Z" level=debug msg="Cannot get keys traefik-ingress/frontends/ Key not found in store "
time="2016-12-27T00:41:16Z" level=debug msg="Cannot get keys traefik-ingress/backends/ Key not found in store "
time="2016-12-27T00:41:16Z" level=debug msg="Configuration received from provider etcd: {}"
time="2016-12-27T00:41:16Z" level=debug msg="Last etcd config received more than 2s, OK"
time="2016-12-27T00:41:16Z" level=info msg="Server configuration reloaded on :80"
time="2016-12-27T00:41:16Z" level=info msg="Server configuration reloaded on :443"
time="2016-12-27T00:41:16Z" level=debug msg="Cannot get keys traefik-ingress/backends/ Key not found in store "
time="2016-12-27T00:41:16Z" level=debug msg="Configuration received from provider etcd: {}"
time="2016-12-27T00:41:16Z" level=info msg="Skipping same configuration for provider etcd"
time="2016-12-27T00:41:16Z" level=debug msg="Transaction ac2d32e8-14c9-4f72-a21c-6cea29be0286 begins"
time="2016-12-27T00:41:16Z" level=debug msg="Load balancer method '<nil>' for backend hello.k8s-otp-01.goabout.com: Invalid method, using default. Using default wrr."
time="2016-12-27T00:41:16Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"hello.k8s-otp-01.goabout.com\":{\"servers\":{\"hello-deployment-1606860626-1dl66\":{\"url\":\"http://10.244.0.9:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"hello.k8s-otp-01.goabout.com\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"hello.k8s-otp-01.goabout.com\",\"routes\":{\"hello.k8s-otp-01.goabout.com\":{\"rule\":\"Host:hello.k8s-otp-01.goabout.com\"}},\"passHostHeader\":true,\"priority\":0}}}"
time="2016-12-27T00:41:16Z" level=debug msg="Last kubernetes config received less than 2s, waiting..."
time="2016-12-27T00:41:16Z" level=debug msg="Received event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[name:kube-scheduler namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-scheduler uid:900bd1e5-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289153 creationTimestamp:2016-12-24T00:33:17Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:17Z\",\"renewTime\":\"2016-12-27T00:41:16Z\",\"leaderTransitions\":0}]] subsets:[]]]"
time="2016-12-27T00:41:17Z" level=debug msg="Skipping event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[name:kube-scheduler namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-scheduler uid:900bd1e5-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289153 creationTimestamp:2016-12-24T00:33:17Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:17Z\",\"renewTime\":\"2016-12-27T00:41:16Z\",\"leaderTransitions\":0}]] subsets:[]]]"
time="2016-12-27T00:41:17Z" level=debug msg="Received event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[name:kube-controller-manager namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager uid:8f10669a-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289154 creationTimestamp:2016-12-24T00:33:15Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:15Z\",\"renewTime\":\"2016-12-27T00:41:17Z\",\"leaderTransitions\":0}]] subsets:[]]]"
time="2016-12-27T00:41:17Z" level=debug msg="Skipping event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:15Z\",\"renewTime\":\"2016-12-27T00:41:17Z\",\"leaderTransitions\":0}] name:kube-controller-manager namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager uid:8f10669a-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289154 creationTimestamp:2016-12-24T00:33:15Z] subsets:[]]]"
time="2016-12-27T00:41:18Z" level=debug msg="Waited for kubernetes config, OK"
time="2016-12-27T00:41:18Z" level=debug msg="Creating frontend hello.k8s-otp-01.goabout.com"
time="2016-12-27T00:41:18Z" level=debug msg="Wiring frontend hello.k8s-otp-01.goabout.com to entryPoint http"
time="2016-12-27T00:41:18Z" level=debug msg="Creating route hello.k8s-otp-01.goabout.com Host:hello.k8s-otp-01.goabout.com"
time="2016-12-27T00:41:18Z" level=debug msg="Creating entryPoint redirect http -> https : ^(?:https?:\\/\\/)?([\\w\\._-]+)(?::\\d+)?(.*)$ -> https://$1:443$2"
time="2016-12-27T00:41:18Z" level=debug msg="Wiring frontend hello.k8s-otp-01.goabout.com to entryPoint https"
time="2016-12-27T00:41:18Z" level=debug msg="Creating route hello.k8s-otp-01.goabout.com Host:hello.k8s-otp-01.goabout.com"
time="2016-12-27T00:41:18Z" level=debug msg="Creating backend hello.k8s-otp-01.goabout.com"
time="2016-12-27T00:41:18Z" level=debug msg="Creating load-balancer wrr"
time="2016-12-27T00:41:18Z" level=debug msg="Creating server hello-deployment-1606860626-1dl66 at http://10.244.0.9:80 with weight 0"
time="2016-12-27T00:41:18Z" level=info msg="Server configuration reloaded on :80"
time="2016-12-27T00:41:18Z" level=info msg="Server configuration reloaded on :443"
time="2016-12-27T00:41:18Z" level=debug msg="Received event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[selfLink:/api/v1/namespaces/kube-system/endpoints/kube-scheduler uid:900bd1e5-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289156 creationTimestamp:2016-12-24T00:33:17Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:17Z\",\"renewTime\":\"2016-12-27T00:41:18Z\",\"leaderTransitions\":0}] name:kube-scheduler namespace:kube-system] subsets:[]]]"
time="2016-12-27T00:41:19Z" level=debug msg="Skipping event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[name:kube-scheduler namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-scheduler uid:900bd1e5-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289156 creationTimestamp:2016-12-24T00:33:17Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:17Z\",\"renewTime\":\"2016-12-27T00:41:18Z\",\"leaderTransitions\":0}]] subsets:[]]]"
time="2016-12-27T00:41:19Z" level=debug msg="Received event from kubernetes map[type:MODIFIED object:map[subsets:[] kind:Endpoints apiVersion:v1 metadata:map[annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:15Z\",\"renewTime\":\"2016-12-27T00:41:19Z\",\"leaderTransitions\":0}] name:kube-controller-manager namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager uid:8f10669a-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289157 creationTimestamp:2016-12-24T00:33:15Z]]]"
time="2016-12-27T00:41:19Z" level=debug msg="Skipping event from kubernetes map[object:map[metadata:map[uid:8f10669a-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289157 creationTimestamp:2016-12-24T00:33:15Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:15Z\",\"renewTime\":\"2016-12-27T00:41:19Z\",\"leaderTransitions\":0}] name:kube-controller-manager namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager] subsets:[] kind:Endpoints apiVersion:v1] type:MODIFIED]"
time="2016-12-27T00:41:20Z" level=debug msg="Received event from kubernetes map[type:MODIFIED object:map[metadata:map[uid:900bd1e5-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289158 creationTimestamp:2016-12-24T00:33:17Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:17Z\",\"renewTime\":\"2016-12-27T00:41:20Z\",\"leaderTransitions\":0}] name:kube-scheduler namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-scheduler] subsets:[] kind:Endpoints apiVersion:v1]]"
time="2016-12-27T00:41:21Z" level=debug msg="Skipping event from kubernetes map[type:MODIFIED object:map[subsets:[] kind:Endpoints apiVersion:v1 metadata:map[annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:17Z\",\"renewTime\":\"2016-12-27T00:41:20Z\",\"leaderTransitions\":0}] name:kube-scheduler namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-scheduler uid:900bd1e5-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289158 creationTimestamp:2016-12-24T00:33:17Z]]]"
time="2016-12-27T00:41:21Z" level=debug msg="Received event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[name:kube-controller-manager namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager uid:8f10669a-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289159 creationTimestamp:2016-12-24T00:33:15Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:15Z\",\"renewTime\":\"2016-12-27T00:41:21Z\",\"leaderTransitions\":0}]] subsets:[]]]"
time="2016-12-27T00:41:21Z" level=debug msg="Skipping event from kubernetes map[type:MODIFIED object:map[kind:Endpoints apiVersion:v1 metadata:map[namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager uid:8f10669a-c970-11e6-9b10-d43d7ebdffc4 resourceVersion:289159 creationTimestamp:2016-12-24T00:33:15Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"k8s-otp-01\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-12-24T00:33:15Z\",\"renewTime\":\"2016-12-27T00:41:21Z\",\"leaderTransitions\":0}] name:kube-controller-manager] subsets:[]]]"
time="2016-12-27T00:41:22Z" level=debug msg="Challenge GetCertificate hello.k8s-otp-01.goabout.com"
time="2016-12-27T00:41:22Z" level=debug msg="Loading ACME certificates [hello.k8s-otp-01.goabout.com]..."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x75b635]

goroutine 403 [running]:
panic(0xd2c680, 0xc420014030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0x0, 0xc4200e78c0, 0xc4200e7860, 0xc4205d9240, 0x1c)
        /go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:557 +0xf5
created by github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges
        /go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:570 +0x113
 ```

Sometimes, the `curl` command just stalls, with (to my eyes) only these interesting log lines:
```shell
time="2016-12-27T00:47:06Z" level=debug msg="Challenge GetCertificate hello.k8s-otp-01.goabout.com" 
time="2016-12-27T00:47:06Z" level=debug msg="Loading ACME certificates [hello.k8s-otp-01.goabout.com]..." 
time="2016-12-27T00:47:06Z" level=debug msg="Challenge Present hello.k8s-otp-01.goabout.com" 
time="2016-12-27T00:47:07Z" level=debug msg="Transaction c68addaf-ffad-4774-9759-47f56ce6c545 begins" 
```

**Comment by ldez** [comment]
Do you still have the same problem with the latest version? [releases](https://github.com/containous/traefik/releases)

**Comment by jcassee** [comment]
I am no longer using Kubernetes. As such I am closing the issue.
