### ISSUE TITLE
systemd socket activation fails with panic: interface conversion: net.Listener is *net.UnixListener, not *net.TCPListener

### ISSUE THREAD

**Issue by oryjkov** [containous/traefik#10924]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

1. Set up a systemd socket
2. created a podman .kube service that references the socket above and uses a yaml kubernetes config with a single container running traefik with a systemd socket
3. started socket + pod
4. observed that traefik crashed

### What did you see instead?

traefik crashes with:
```
panic: interface conversion: net.Listener is *net.UnixListener, not *net.TCPListener
```

### What version of Traefik are you using?

v3.1.0

### What is your environment & configuration?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    name: traefik
spec:
  containers:
  - args:
      - '--entrypoints.sockact'
      - '--log.level=debug'
    name: traefik
    image: docker.io/library/traefik:v3.1.0
```

systemd socket:
```
[Unit]
Description=traefik socket

[Socket]
ListenStream=0.0.0.0:2083
FileDescriptorName=sockact
Service=traefik.service

[Install]
WantedBy=sockets.target
```

systemd service:
```
[Unit]
Description=traefik pod
Wants=network-online.target
After=network-online.target
Requires=traefik.socket
After=traefik.socket

[Kube]
Yaml=traefik.yaml
AutoUpdate=registry
Network=none

[Install]
WantedBy=default.target
```

### If applicable, please paste the log output in DEBUG level

```
2024-07-21T22:31:51Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:101 > Traefik version 3.1.0 built on 2024-07-15T14:44:04Z version=3.1.0
2024-07-21T22:31:51Z DBG github.com/traefik/traefik/v3/cmd/traefik/traefik.go:108 > Static configuration loaded [json] staticConfiguration={"entryPoints":{"sockact1":{"forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"tra
nsport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s","readTimeout":"1m0s"}},"udp":{"timeout":"3s"}}},"global":{"checkNewVersion":true},"log":{"format":"common","level":"debug"},"providers":{"providersThrott
leDuration":"2s"},"serversTransport":{"maxIdleConnsPerHost":200},"tcpServersTransport":{"dialKeepAlive":"15s","dialTimeout":"30s"}}
2024-07-21T22:31:51Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:617 >
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/

panic: interface conversion: net.Listener is *net.UnixListener, not *net.TCPListener

goroutine 1 [running]:
github.com/traefik/traefik/v3/pkg/server.buildListener({0x69ba6a0, 0xc001ed9230}, {0xc001e6e954, 0x8}, 0xc001e86400)
        github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:490 +0x2c6
github.com/traefik/traefik/v3/pkg/server.NewTCPEntryPoint({0x69ba6a0, 0xc001ed9230}, {0xc001e6e954, 0x8}, 0xc001e86400, 0x0, {0x69a5230, 0xc001ecab40})
        github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:183 +0xf6
github.com/traefik/traefik/v3/pkg/server.NewTCPEntryPoints(0xc001d83710, 0x0, {0x69f0958, 0xc001e906e0})
        github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:124 +0x4d6
main.setupServer(0xc001dfe000)
        github.com/traefik/traefik/v3/cmd/traefik/traefik.go:213 +0x754
main.runCmd(0xc001dfe000)
        github.com/traefik/traefik/v3/cmd/traefik/traefik.go:117 +0x2b4
main.main.func1({0xc001da0c00?, 0xc0000b40a0?, 0x10?})
        github.com/traefik/traefik/v3/cmd/traefik/traefik.go:65 +0x19
github.com/traefik/paerser/cli.run(0xc001dac680, {0xc0000b40a0, 0x0?, 0x2})
        github.com/traefik/paerser@v0.2.0/cli/commands.go:133 +0x243
github.com/traefik/paerser/cli.execute(0xc001dac680, {0xc0000b4080, 0x4, 0x4}, 0x28?)
        github.com/traefik/paerser@v0.2.0/cli/commands.go:76 +0x6cf
github.com/traefik/paerser/cli.Execute(...)
        github.com/traefik/paerser@v0.2.0/cli/commands.go:51
main.main()
        github.com/traefik/traefik/v3/cmd/traefik/traefik.go:81 +0x554
```

Process environment:
```shell
$ podman exec -it traefik-traefik sh
/ # ls -la /proc/1/fd
total 0
dr-x------    2 root     root             9 Jul 21 22:30 .
dr-xr-xr-x    9 root     root             0 Jul 21 22:30 ..
lrwx------    1 root     root            64 Jul 21 22:30 0 -> /dev/null
l-wx------    1 root     root            64 Jul 21 22:30 1 -> pipe:[15227679]
l-wx------    1 root     root            64 Jul 21 22:30 2 -> pipe:[15227680]
lrwx------    1 root     root            64 Jul 21 22:30 3 -> socket:[15228364]
lrwx------    1 root     root            64 Jul 21 22:30 4 -> socket:[15230162]
lrwx------    1 root     root            64 Jul 21 22:30 5 -> anon_inode:[eventpoll]
lr-x------    1 root     root            64 Jul 21 22:30 6 -> pipe:[15227690]
l-wx------    1 root     root            64 Jul 21 22:30 7 -> pipe:[15227690]
lrwx------    1 root     root            64 Jul 21 22:30 8 -> socket:[15228363]
/ # cat /proc/1/environ
HOSTNAME=traefikSHLVL=1HOME=/rootLISTEN_PID=1LISTEN_FDS=2container=podmanPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binLISTEN_FDNAMES=sockact:sockact1PWD=// #
```

**Comment by rtribotte** [comment]
Hello @oryjkov,

Thanks for your feedback, we are keeping the issue because we took a look at the code and we think it could be more resilient in that case.

**Comment by Deln0r** [comment]
@rtribotte @kevinpollet — picking this one up. Want to confirm direction before code.

`buildListener` in `pkg/server/server_entrypoint_tcp.go` unconditionally asserts the socket-activation listener to `*net.TCPListener`. `populateSocketActivationListeners` stores whatever `net.FileListener` returns, so when systemd (or podman Quadlet here) hands us an AF_UNIX fd named after an entrypoint, we panic.

Your "more resilient" reading sounds defensive rather than feature. Plan: detect non-TCP early (in `populateSocketActivationListeners` or just before the assertion) and return a clear error like `socket activation listener for entrypoint %q has unexpected type %T, want *net.TCPListener`. Same behavior on the happy path. Diff under ~50 lines plus a unit test.

The bigger alternative — accepting unix-socket entrypoints as a real feature (new scheme, non-keepalive wrapper, ProxyProtocol/TLS/HTTP3 semantics, docs) — is a much wider change. Confirm you meant the smaller one?

**Comment by kevinpollet** [comment]
Hello @Deln0r,

By being more resilient, we meant that an error should be returned instead of having a panic.
Returning the error just before the assertion is fine.
