### ISSUE TITLE
Concurrency issue with provider <-> startServer routine

### ISSUE THREAD

**Issue by janeczku** [containous/traefik#128]
After commit 16047862850b354367790966729cf4f35b80a7f4 running traefik may cause a runtime error in some cases.

Steps to reproduce:
> $ traefik fixtures/file/simple.toml

Since Go doesn't guarantee when a routine is executed, the `serverLock sync.Mutex` introduced in PR #126 doesn't prevent the following:

Main locks the `serverLock` and prepares the initial server
```GO
	serverLock.Lock()
	srv, er = prepareServer(configurationRouter, globalConfiguration, nil, loggerMiddleware, metrics)
```
Meanwhile a provider wants to create a new server and gets blocked on the `serverLock`
```GO
				newConfigurationRouter, err := LoadConfig(newConfigurations, globalConfiguration)
				if err == nil {
					serverLock.Lock()
```
Main dispatches the initial `startServer` routine and unlocks the mutex
```GO
	go startServer(srv, globalConfiguration)
	serverLock.Unlock()
```
Provider routine gets unblocked and then passes `srv` to `prepareServer()` **before** the initial `startServer` routine for `srv` has been executed. As a result `oldServer.HijackListener()` is invoked on a server that doesn't have a listener yet.

```TEXT
DEBU[2015-11-24T17:24:55Z] Global configuration loaded &{Port::80 GraceTimeOut:10 AccessLogsFile: TraefikLogsFile: Certificates:[] LogLevel:DEBUG ProvidersThrottleDuration:2s Docker:<nil> File:0xc820132340 Web:<nil> Marathon:<nil> Consul:<nil> Etcd:<nil> Zookeeper:<nil> Boltdb:<nil>}
INFO[2015-11-24T17:24:55Z] Starting provider *provider.File &{baseProvider:{Watch:false Filename:fixtures/file/simple.toml}}
INFO[2015-11-24T17:24:55Z] Preparing server
INFO[2015-11-24T17:24:55Z] Configuration receveived from provider file: &types.Configuration{Backends:map[string]*types.Backend{"backend1":(*types.Backend)(0xc8201333a0), "backend2":(*types.Backend)(0xc820133860)}, Frontends:map[string]*types.Frontend{"frontend1":(*types.Frontend)(0xc820133cc0), "frontend2":(*types.Frontend)(0xc820164040)}}
INFO[2015-11-24T17:24:55Z] Last file config received more than 2s, OK
DEBU[2015-11-24T17:24:55Z] Creating frontend frontend1
DEBU[2015-11-24T17:24:55Z] Creating route test_1 Host:test.localhost
DEBU[2015-11-24T17:24:55Z] Creating backend backend2
INFO[2015-11-24T17:24:55Z] Creating load-balancer drr
INFO[2015-11-24T17:24:55Z] Creating server server2 http://172.17.0.5:80
INFO[2015-11-24T17:24:55Z] Creating server server1 http://172.17.0.4:80
DEBU[2015-11-24T17:24:55Z] Creating frontend frontend2
DEBU[2015-11-24T17:24:55Z] Creating route test_2 Path:/test
DEBU[2015-11-24T17:24:55Z] Creating backend backend1
INFO[2015-11-24T17:24:55Z] Creating load-balancer wrr
INFO[2015-11-24T17:24:55Z] Creating server server1 http://172.17.0.2:80
INFO[2015-11-24T17:24:55Z] Creating server server2 http://172.17.0.3:80
INFO[2015-11-24T17:24:55Z] Creating circuit breaker NetworkErrorRatio() > 0.5
INFO[2015-11-24T17:24:55Z] Preparing server
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x567830]

goroutine 9 [running]:
github.com/emilevauge/traefik/vendor/github.com/mailgun/manners.(*GracefulListener).Clone(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/emilevauge/traefik/vendor/github.com/mailgun/manners/listener.go:105 +0x40
github.com/emilevauge/traefik/vendor/github.com/mailgun/manners.(*GracefulServer).HijackListener(0xc8201762c0, 0xc82000fe60, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/emilevauge/traefik/vendor/github.com/mailgun/manners/server.go:197 +0x46
main.prepareServer(0xc82015ce10, 0xc8200fd810, 0xc8201762c0, 0xc82016fed8, 0x2, 0x2, 0x0, 0x0, 0x0)
	/go/src/github.com/emilevauge/traefik/traefik.go:285 +0x827
main.main.func2(0xc82000e9c0, 0xc8200fd810, 0xc8200a3350, 0xc8200240e8, 0xc8200240e0, 0xc8200240f8)
	/go/src/github.com/emilevauge/traefik/traefik.go:133 +0x68c
created by main.main
	/go/src/github.com/emilevauge/traefik/traefik.go:150 +0xae2

goroutine 1 [chan receive]:
main.main()
	/go/src/github.com/emilevauge/traefik/traefik.go:214 +0x170f
(...)
```

/cc @vdemeester @emilevauge

**Comment by emilevauge** [comment]
This has been fixed by a `server.go` refactoring ;)

**Comment by janeczku** [comment]
🎉 😄  @emilevauge
