### ISSUE TITLE
Prometheus metrics break config reload

### ISSUE THREAD

**Issue by tcolgate** [containous/traefik#1363]
### What version of Traefik are you using (`traefik version`)?
master

### What is your environment & configuration (arguments, toml...)?
marathon

### What did you do?
Enable marathon
Enable prometheus web stats
Run traeffik
Deploy app

### What did you expect to see?
Traeffik should spot the upadtes, regenerate the configuration, and reload

### What did you see instead?
An exception after the deploy and config update appearing

```DEBU[2017-03-29T15:38:09Z] Creating load-balancer wrr                   
DEBU[2017-03-29T15:38:09Z] Creating loadd-balancer connlimit            
ERRO[2017-03-29T15:38:09Z] Error in Go routine: duplicate metrics collector registration attempted 
goroutine 57 [running]:
runtime/debug.Stack(0x6d21af, 0xc42004c240, 0x1e602ee)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x1c534e0, 0xc4207a7700)
        /go/src/github.com/containous/traefik/safe/routine.go:147 +0x7d
github.com/containous/traefik/safe.GoWithRecover.func1.1(0x1ecd948)
        /go/src/github.com/containous/traefik/safe/routine.go:138 +0x57
panic(0x1c534e0, 0xc4207a7700)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/containous/traefik/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc42004d780, 0xc4201e9ec0, 0x1, 0x1)
        /go/src/github.com/containous/traefik/vendor/github.com/prometheus/client_golang/prometheus/registry.go:404 +0x92
github.com/containous/traefik/vendor/github.com/prometheus/client_golang/prometheus.MustRegister(0xc4201e9ec0, 0x1, 0x1)
        /go/src/github.com/containous/traefik/vendor/github.com/prometheus/client_golang/prometheus/registry.go:152 +0x53
github.com/containous/traefik/vendor/github.com/go-kit/kit/metrics/prometheus.NewCounterFrom(0x0, 0x0, 0x0, 0x0, 0x1e5fb41, 0x16, 0x1ea0c0b, 0x48, 0xc4203e4720, 0xc4207a7580, ...)
        /go/src/github.com/containous/traefik/vendor/github.com/go-kit/kit/metrics/prometheus/prometheus.go:24 +0xed
github.com/containous/traefik/middlewares.NewPrometheus(0xc4203a5410, 0x5, 0xc4203e3980, 0xc4203e46f0)
        /go/src/github.com/containous/traefik/middlewares/prometheus.go:42 +0x214
main.(*Server).loadConfig(0xc4207c2ea0, 0xc420abdec0, 0xa, 0x101, 0x0, 0x0, 0x0, 0x0, 0x1e3e68d, 0x5, ...)
        /go/src/github.com/containous/traefik/server.go:733 +0x1c32
main.(*Server).listenConfigurations(0xc4207c2ea0, 0xc4205d4770)
        /go/src/github.com/containous/traefik/server.go:294 +0x36d
main.(*Server).Start.func2(0xc4205d4770)
        /go/src/github.com/containous/traefik/server.go:103 +0x34
github.com/containous/traefik/safe.(*Pool).Go.func1()
        /go/src/github.com/containous/traefik/safe/routine.go:77 +0x3a
github.com/containous/traefik/safe.GoWithRecover.func1(0x1ecd948, 0xc4202e0ff0)
        /go/src/github.com/containous/traefik/safe/routine.go:141 +0x4d
created by github.com/containous/traefik/safe.GoWithRecover
        /go/src/github.com/containous/traefik/safe/routine.go:142 +0x49
```
after this, additional configuration changes no longer result in the configuration changing.

This should be a fairly easy fix (don't use MustRegister, and check the error), however, there may be a better way to manage the prometheus metrics (using a custom collector, rather than a registry), I'm happy to investigate this.

**Comment by tcolgate** [comment]
probably should mention that remove 
```
[web.metrics.prometheus]
Buckets=[0.1,0.3,1.2,5.0]
```

fixes the problem

**Comment by tcolgate** [comment]
Closing, this seems to have been fixed in 1.2, but isn't present on master. Presumably you aren't using the master branch.

**Comment by emilevauge** [comment]
I am in the process of merging 1.2 branch back to master branch ;)

**Comment by tcolgate** [comment]
@emilevauge the merge hasn't happened yet as far as I can see, so master is still broken. Is the branch/merge strategy documented anywhere?

**Comment by timoreimann** [comment]
It's on master now.

A bit of documentation is likely due, but things have been in the flux lately.
