### ISSUE TITLE
Traefik panics due to ACME

### ISSUE THREAD

**Issue by m4ng0squ4sh** [containous/traefik#269]
Traefik panicked due to a certificate renew request.

```
goroutine 44 [running]:
panic(0xc119c0, 0xc82000a080)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/containous/traefik/acme.(*ACME).renewCertificates(0xc820068880, 0xc820089320, 0xc8200df680, 0x0, 0x0)
	/go/src/github.com/containous/traefik/acme/acme.go:293 +0x871
github.com/containous/traefik/acme.(*ACME).CreateConfig.func2(0xc8202eb340, 0xc820068880, 0xc820089320, 0xc8200df680)
	/go/src/github.com/containous/traefik/acme/acme.go:253 +0x91
created by github.com/containous/traefik/acme.(*ACME).CreateConfig
	/go/src/github.com/containous/traefik/acme/acme.go:259 +0x7ea
```

**Comment by emilevauge** [comment]
This is bad...
I created the PR #270 that fixes this issue.
Can you try it ?

**Comment by m4ng0squ4sh** [comment]
Great! Thank you for the quick response! However the panic is not easily reproduceable. Traefik crashed over the night...
