### ISSUE TITLE
Manually trigger Traefik to generate letsencrypt certificate using API

### ISSUE THREAD

**Issue by hussam-almarzoq** [containous/traefik#3652]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The idea is I want to be able to ask Traefik to generate certificates based on an API call. Our system has a lot of domain names that are dynamically pointed to Traefik, so to make sure we don't exceed letsencrypt we want to manually trigger traefik.

**Comment by dtomcej** [comment]
If you are going to be manually managing your LE certificates, why not use a tool like certbot to generate certificates, then just dynamically add them to Traefik?

**Comment by hussam-almarzoq** [comment]
Actually, I just want to trigger Traefik and let it do the rest. Otherwise, I’ll have to take care of the setup for the challenge.

**Comment by jnovack** [comment]
I can see OP's purpose, but I think the answer lies in #3653, as it was stated the real issue is "not exceeding Let's Encrypt api limits".

Although, this problem only exists once, on go-live.  In which case, I heavily recommend a phased deployment.  Add a website (container/backend/etc), then generate it's certificate, test it, repeat.

This becomes VERY easy with `acme.OnHostRule = true`.

**Comment by hussam-almarzoq** [comment]
Is it possible to use labels to enable OnHostRule for specific frontend?

**Comment by soupdiver** [comment]
I came across the same need. My scenario:
I run a GKE cluster with a `traefik-ingress-controller`.

The `traefik-ingress-controller-service` creates a LoadBalancer on GCE and routes traffic into traefik and from there it gets forwarded to my services.

The issue: When LoadBalancer is created it has a health check attached. No traffic gets through the LoadBalancer until the HealthCheck is green. Since traefik requests the LE certificates immediately after launch (and does not retry in error case) there is not enough time for the health check to get green and allow initial traffic into the cluster for the `http challenge`.

Currently I have to kill the pod and hope that the newly created one is ready fast enough to do the challenge.

A wait time for the LE process, a retry or API endpoint to trigger would really help

**Comment by porridge** [comment]
@soupdiver I think I'm facing the same issue as you. Were you able find any reliable workaround?

**Comment by porridge** [comment]
FTR, there seems to be a separate issue https://github.com/containous/traefik/issues/2174 for the thing described by @soupdiver above.

**Comment by b0r1sp** [comment]
Quick workaround: 

1.  delete either complete acme.json or individual certs inside file
2. restart traefik

**Comment by b0r1sp** [comment]
Beside the mentioned API-call I'd really wish to see a button in the dashboard which enables to force-renew individual certs.

**Comment by fireba11** [comment]
It would also be handy to have a shell/CLI command to do that.
My current case was i had some issues causing me to restart traefik quite a few times, causing the rate limiter to kick in.
The LE certificate was only used for the traefik dashboard, not for my production but i still had to restart traefik to get it renewed ...

**Comment by Fmstrat** [comment]
I bet everyone wishes this had been implemented today after the intermediate cert expired. Anyone else stuck in a "now what" moment?

**Comment by ptruman** [comment]
I deleted acme.json to try to force a regen, and now I'm getting this:

time="2021-10-03T16:33:00+01:00" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2021-10-03T16:33:00+01:00" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2021-10-03T16:33:00+01:00" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2021-10-03T16:33:00+01:00" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2021-10-03T16:33:00+01:00" level=error msg="Stack: goroutine 122 [running]:\nruntime/debug.Stack()\n\t/usr/local/golang/1.10.8/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x2d787c0, 0x593
07b0})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x36\npanic({0x2d787c0,
 0x59307b0})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).getUncheckedDomains(0xc000352600, {0x38ed8e0, 0xc000c71c50}, {0xc000e32e60, 0x1, 0x1}, {0x3322370, 0x7})\n\t/home/s
emaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:685 +0x1bf\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).resolveCertificate(0xc000352600, {0x38ed8e0, 0xc000c71c50}, {{0x0, 0x0}, {0xc000dd27c0, 0x1, 0x1}}, {0x33223
70, 0x7})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:460 +0x117\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).watchNewDomains.func1.2()\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/provi
der/acme/provider.go:431 +0x72\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\t/home/sema
phore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x77\n"

**Comment by Austreelis** [comment]
@ptruman I encountered the same issue, so I replaced `acme.json` with the following:

```json
{
  "le": {
    "Account": {
      "Email": "mail@example.com",
      "Registration": {
        "body": {
          "status": "invalid",
          "contact": [
            "mailto:mail@examplel.com"
          ]
        }
      }
    }
  }
}
```

And traefik did correctly re-generate all certificates.

**Comment by konstantin-schura** [comment]
It will be good to have possibility to manually renew le certs. My certs are valid only for 10 days, it was issue with aws policy, i fixed it and need to check. I need to wait next auto renew. It is no possible to me to remove old ones and restart) It is working server.

**Comment by tomMoulard** [comment]
Hello @konstantin-schura,

> It will be good to have possibility to manually renew le certs. My certs are valid only for 10 days

There is a PR (#8046) that will allow you to set the certificate duration. This feature will be available in the next minor release of Traefik.
In your use case, you'll have to set `--certificatesresolvers.myresolver.acme.certificatesduration=240` in order to renew certs with the right timeframes.

**Comment by bodomic2** [comment]
Thanks for the solution @Austreelis, but I think there is no way to reissue 100+ certificates in one account in so short timeframe anyways...
I feel like bunch of websites will go nuts these days. (came here after a letter about TLS-ALPN-01 validation method revocation)

**Comment by darkl0rd** [comment]
This is exactly my concern - I have a bunch of certificates in use which will be revoked as per recent mailing and am looking for a way to pre-emptively (in a controlled manner) renew these certificates (without causing downtime); any way to do this?

**Comment by bodomic2** [comment]
@darkl0rd , LE staff offers some help here - https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449/24 - also saying that limit will be 300 orders per 3 hours which is quite high. I remember hitting limit of 50/week, and I'm a bit puzzled by this new information

**Comment by darkl0rd** [comment]
Thanks for that - my problem is, I run a large scale enterprise grade service - I can't have our customers end up with warnings either; that will cause a sh*tstorm with our support department. I can't remove the existing certificates either, because then I will have downtime, so I am really looking for a way to tell traefik - renew the certificates which are here; regardless of the expiry date.

**Comment by bodomic2** [comment]
@darkl0rd - I'm quite positive you can feed traefik with information that certificates 'need to be updated 2 days after issuance" - seen this hint somewhere here or there. I'm pretty sure this will solve the problem for you.
PS: please let me know if you find the exact HowTo do that :)

**Comment by jgerken** [comment]
@darkl0rd I used a workaround with Træfik 1.7 (it should be possible with Træfik 2.X, too), I deleted only the `Certificate` lines from my `acme.json` and restarted Træfik. All certificates are renewed then. Downtime is minimal, at most some seconds for the renewal of the certificates. This workaround also gives you control about how many certificates are renewed at once. Not sure if this minimal downtime is acceptable for you or not and yes it is not very handy and Træfik should have a build-in mechanism for this but it was the best I could do in a controlled manner.

**Comment by bodomic2** [comment]
@jgerken, thanks, this was my idea also.

**Comment by darkl0rd** [comment]
I really need to avoid -any- downtime - I have 1000's of live connections to remote agents that are processing data. I'm also running 1.7, my config is stored in Consul.

**Comment by ldez** [comment]
For people that need help to clean their `acme.json` file, I quickly created a simple tool to help to remove your certificates from the `acme.json` (Traefik v2 only).
https://github.com/ldez/traefik-certs-cleaner/

The process:
- run the tool with the right arguments
- copy the content of the generated file to your `acme.json` file
- restart Traefik

@darkl0rd for Traefik v1, the clean is a bit more complex but there are possibilities.
In all cases, at some point, you will have to restart your Traefik instances.

FYI I'm a Traefik maintainer.

**Comment by jgerken** [comment]
@ldez could the tool be extended so that is does the actual renewal of the certificates? That would allow users to generate a fixed version of the `acme.json` "offline" and only have the minimal downtime of the Træfik restart? My instances are small and do not require such a solution but I think it would be really helpful for users with large instances.

**Comment by ldez** [comment]
> could the tool be extended so that is does the actual renewal of the certificates?

Technically yes, it's more complex because the only information that I can use is the `acme.json` file, but yes it can be possible.

Note: a restart will be required in all cases.

**Comment by jgerken** [comment]
> It's more complex because the only information that I can use is the `acme.json` file, and the TLS challenge requires exposing a temporary certificate for the domain on 443.

Ah, yes. Didn't think about that. Sorry!

**Comment by bodomic2** [comment]
> @ptruman I encountered the same issue, so I replaced `acme.json` with the following:
> 
> ```json
> {
>   "le": {
>     "Account": {
>       "Email": "mail@example.com",
>       "Registration": {
>         "body": {
>           "status": "invalid",
>           "contact": [
>             "mailto:mail@examplel.com"
>           ]
>         }
>       }
>     }
>   }
> }
> ```
> 
> And traefik did correctly re-generate all certificates.

Just tried this one, with my email in both cases, of course.
All of the certificates tried to re-issue and failed with error 'illegal character in email domain' or something like that...
Tried also copying the 'working' json from current running config & updating it to this form (just to make sure there are no hidden characters etc) - same error.

**Comment by bodomic2** [comment]
> For people that need help to clean their `acme.json` file, I quickly created a simple tool to help to remove your certificates from the `acme.json` (Traefik v2 only)

I'm sorry but can you also provide an instruction how to build it? I'm total zero in golang and trying to setup golang-lint with berserk googling of all encountered errors just got stuck in the very beginning with
`ERRO Running error: unknown linters: 'cyclop,paralleltest,ifshort,varnamelen,nilnil', run 'golangci-lint linters' to see the list of supported linters`

**Comment by bodomic2** [comment]
> I encountered the same issue, so I replaced `acme.json` with the following:
Struggled some time, trying to use this example, finally I did this: 
Opened acme.json and cleared all the array `Certificates: []` - leaving in place my private key and url to my account.
Only doing so it worked.

**Comment by ldez** [comment]
**I'm going to repeat my post because I'm afraid people who need a quick fix won't see it because of the discussion**

For people that need help to clean their `acme.json` file, I quickly created a simple tool to help to remove your certificates from the `acme.json` (Traefik v2 only).

https://github.com/ldez/traefik-certs-cleaner/

The process:
- run the tool with the right arguments
- copy the content of the generated file to your `acme.json` file
- restart Traefik

The readme contains examples for all the options (only 3 options).

https://github.com/traefik/traefik/issues/3652#issuecomment-1022423896

**Comment by benok** [comment]
@bodomic2 wrote:
>Struggled some time, trying to use this example, finally, I did this:
>Opened acme.json and cleared all the array Certificates: [] - leaving in place my private key and url to my account.

This can be done with [jq](https://stedolan.github.io/jq/) like this.

```sh
$ cp -p acme.json acme.json.bk
$ cat acme.json | jq 'del(.letsencrypt.Certificates)' | jq '.letsencrypt |= .+ {"Certificates":[]}' > acme-new.json
$ mv acme-new.json acme.json
```
And don't forget that acme.json requires 600 permission. (like me :-)
```sh
$ chmod 600 acme.json
```

**Comment by brablc** [comment]
> If you are going to be manually managing your LE certificates, why not use a tool like [Certbot](https://github.com/certbot/certbot) to generate certificates, then just dynamically add them to Traefik?

I think this is actually the only reliable way at the moment, I built a drop-in solution for `docker swarm`: https://github.com/brablc/swarm-certbot-traefik

**Comment by nmengin** [comment]
Hello there,

This would not make it to our roadmap as we are focused elsewhere.  If a community member would like to build it, let us know, and we will work with you to ensure you have all the information needed to merge it.  

We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process.  Let us know here or create a PR before you start, and we will work with you there.  

Don’t forget to check out the [contributor docs](https://github.com/traefik/contributors-guide/blob/master/pr_guidelines.md) and link the PR to this issue.
