### ISSUE TITLE
500 on grpc without ssl (version 17+)

### ISSUE THREAD

**Issue by itielshwartz** [containous/traefik#3786]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

python greeter_client.py

### What did you expect to see?

`Greeter client received: Hello, you!`

### What did you see instead?

```Traceback (most recent call last):
  File "greeter_client.py", line 18, in <module>
    run()
  File "greeter_client.py", line 13, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 500, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.CANCELLED, Received http2 header with status: 500)>
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.0-rc3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
debug=true

[entryPoints]
  [entryPoints.http]
  address = ":50052"

[api]

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    # Access on backend with h2c
    url = "h2c://host.docker.internal:50051"


[frontends]
  [frontends.frontend1]
  backend = "backend1"
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-08-19T06:17:14Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2018-08-19T06:17:14Z" level=info msg="Traefik version v1.7.0-rc3 built on 2018-08-01_01:37:51PM"
time="2018-08-19T06:17:14Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-08-19T06:17:14Z" level=debug msg="Global configuration loaded "
time="2018-08-19T06:17:14Z" level=info msg="Preparing server http &{Address::50052 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc42046e300} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-08-19T06:17:14Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc42046e340} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-08-19T06:17:14Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2018-08-19T06:17:14Z" level=info msg="Starting server on :50052"
time="2018-08-19T06:17:14Z" level=info msg="Starting server on :8080"
time="2018-08-19T06:17:14Z" level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Directory\":\"\",\"TraefikFile\":\"/etc/traefik/traefik.toml\"}"
time="2018-08-19T06:17:14Z" level=debug msg="Backend backend1: no load-balancer defined, fallback to 'wrr' method"
time="2018-08-19T06:17:14Z" level=debug msg="Configuration received from provider file: {\"backends\":{\"backend1\":{\"servers\":{\"server1\":{\"url\":\"h2c://host.docker.internal:50051\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend1\":{\"entryPoints\":[\"http\"],\"backend\":\"backend1\",\"priority\":0,\"basicAuth\":null}}}"
time="2018-08-19T06:17:14Z" level=debug msg="Wiring frontend frontend1 to entryPoint http"
time="2018-08-19T06:17:14Z" level=debug msg="Creating backend backend1"
time="2018-08-19T06:17:14Z" level=debug msg="Creating load-balancer wrr"
time="2018-08-19T06:17:14Z" level=debug msg="Creating server server1 at h2c://host.docker.internal:50051 with weight 0"
time="2018-08-19T06:17:14Z" level=info msg="Server configuration reloaded on :50052"
time="2018-08-19T06:17:14Z" level=info msg="Server configuration reloaded on :8080"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/Greeter/SayHello\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-python/1.12.1 grpc-c/6.0.0 (osx; chttp2; glorious)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:50052\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:39690\",\"RequestURI\":\"/Greeter/SayHello\",\"TLS\":null}"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/Greeter/SayHello\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-python/1.12.1 grpc-c/6.0.0 (osx; chttp2; glorious)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:50052\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:39690\",\"RequestURI\":\"/Greeter/SayHello\",\"TLS\":null}" ForwardURL="h2c://host.docker.internal:50051"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"host.docker.internal:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-python/1.12.1 grpc-c/6.0.0 (osx; chttp2; glorious)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:50052\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:39690\",\"RequestURI\":\"/Greeter/SayHello\",\"TLS\":null}"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"host.docker.internal:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-python/1.12.1 grpc-c/6.0.0 (osx; chttp2; glorious)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:50052\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:39690\",\"RequestURI\":\"/Greeter/SayHello\",\"TLS\":null}"
time="2018-08-19T06:17:28Z" level=debug msg="'500 Internal Server Error' caused by: stream error: stream ID 3; INTERNAL_ERROR"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/forward/http: Round trip: h2c://host.docker.internal:50051, code: 500, Length: 21, duration: 2.899866ms"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"host.docker.internal:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-python/1.12.1 grpc-c/6.0.0 (osx; chttp2; glorious)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:50052\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:39690\",\"RequestURI\":\"/Greeter/SayHello\",\"TLS\":null}"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"host.docker.internal:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-python/1.12.1 grpc-c/6.0.0 (osx; chttp2; glorious)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:50052\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:39690\",\"RequestURI\":\"/Greeter/SayHello\",\"TLS\":null}"
time="2018-08-19T06:17:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/Greeter/SayHello\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-python/1.12.1 grpc-c/6.0.0 (osx; chttp2; glorious)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:50052\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:39690\",\"RequestURI\":\"/Greeter/SayHello\",\"TLS\":null}"
time="2018-08-19T06:17:32Z" level=info msg="I have to go..."
time="2018-08-19T06:17:32Z" level=info msg="Stopping server gracefully"
time="2018-08-19T06:17:32Z" level=debug msg="Waiting 10s seconds before killing connections on entrypoint traefik..."
time="2018-08-19T06:17:32Z" level=debug msg="Waiting 10s seconds before killing connections on entrypoint http..."
time="2018-08-19T06:17:32Z" level=debug msg="Entrypoint traefik closed"
time="2018-08-19T06:17:42Z" level=debug msg="Wait hijack connection is over due to: context deadline exceeded"
time="2018-08-19T06:17:42Z" level=error msg="Error while closing Hijacked conn: close tcp 172.17.0.2:50052->172.17.0.1:39690: use of closed network connection"
time="2018-08-19T06:17:42Z" level=debug msg="Entrypoint http closed"
time="2018-08-19T06:17:42Z" level=info msg="Server stopped"
time="2018-08-19T06:17:42Z" level=info msg="Shutting down"
```

The code i used is GPRC offical server adn client: https://github.com/grpc/grpc/tree/master/examples/python/helloworld

**Comment by traefiker** [comment]
Closed by #3824.
