### ISSUE TITLE
Build a Linux RPM package with dashboard assets

### ISSUE THREAD

**Issue by drpaneas** [containous/traefik#4382]
### Feature

- Provide sources in a way where the required assets are already present inside the `tarball`.
- Write instructions how to compile Traefik utilizing these assets.

If this is not possible (maybe due to the size of the assets), then please write instructions how to generate **without** using docker.

### What did you expect to see?

Something like:

1. Download the sources
2. Install go-bindata (or fetch its binary)
3. Run `this` command to compile it with the assets (outside of Docker).

### My try-out

Building `traefik` without dashboard was an easy task to do. You can find my RPM [here](https://download.opensuse.org/repositories/home:/pgeorgiadis/openSUSE_Tumbleweed/x86_64/traefik-1.7.7-1.1.x86_64.rpm) and see my [spec](https://build.opensuse.org/package/view_file/home:pgeorgiadis/traefik/traefik.spec?expand=1&rev=8963ae390c7014f07c3a0be524e9df01) file.

What I did is:

* Fetch the sources [traefik](https://github.com/containous/traefik) and [go-bindata](https://github.com/containous/go-bindata)

* Configure the environment of the virtual-machine:

```bash
export GOPATH=$HOME/go; mkdir $GOPATH
export GOBIN=$GOPATH/bin; mkdir $GOBIN
export PATH=$PATH:$GOBIN
```

* Generate the `go-bindata` binary that is required later

```bash
cd $HOME/go/src/github.com/containous/go-bindata
go build -v -ldflags '-X "main.AppVersion=1.0.0"' -o dist/go-bindata ./go-bindata/
cp dist/go-bindata $GOBIN
```

* Go to the sources of traefik and build it

```bash
cd $HOME/go/src/traefik
go generate
go build ./cmd/traefik
```

* Once it's done, place the binary to the `/usr/bin/traefik` 

```
install -D -m 0755 %{name} %{buildroot}%{_bindir}/%{name}
```

Now, this works fine. What I am trying to do now is pretty much the same thing, but including the assets for the web dashboard. However I think I am doing something wrong, but please be so kind to correct my mistakes. From what I see in the `Makefile` the target is `binary` but I need to replicate all the steps outside of a docker container -- and if there are any files that need to be downloaded from the Internet, I need to have them already there present.

So, makefile says:

```
In order to build traefik binary WITH the webui dashboard you have to type:
 
make -n binary
 
 
This does this:
 
docker build -t traefik-webui -f webui/Dockerfile webui
if [ ! -d "static" ]; then \
  mkdir -p static; \
  docker run --rm -v "$PWD/static":'/src/static' traefik-webui npm run build; \
  echo 'For more informations show `webui/readme.md`' > $PWD/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md; \
fi
mkdir dist
docker build  -t "traefik-dev:master" -f build.Dockerfile .
docker run  -e "TEST_CONTAINER=1" -v "/var/run/docker.sock:/var/run/docker.sock" -it -e OS_ARCH_ARG -e OS_PLATFORM_ARG -e TESTFLAGS -e VERBOSE -e VERSION -e CODENAME -e TESTDIRS -e CI -e CONTAINER=DOCKER -v "/home/tux/obs/home:pgeorgiadis/traefik/traefik/"dist":/go/src/github.com/containous/traefik/"dist"" "traefik-dev:master" ./script/make.sh generate binary
```

Let me show you what I did:

* After generating the go-bindata (see my previous steps, building traefik without  dashboard) then prepare the assets:

```bash
zypper in npm # opensuse packager
zypper in yarn # opensuse packager
cp webui/yarn.lock static/
cp webui/package.json static/
cd static 
npm set progress=false
yarn install
```

* This created a folder 'node_modules' (static/node_modules) hopefully this all that it needs.

* Now build traefik (it should pick the assets since they are there)
```bash
cd $HOME/go/src/traefik
go generate
go build ./cmd/traefik
```

The build fails though, complaining about OOM killer:

```
[  142s] # github.com/containous/traefik/autogen/genstatic
[  142s] runtime: out of memory: cannot allocate 368640-byte block (43350163456 in use)
[  142s] fatal error: out of memory
```

Full log can be found at:

```
   39s] removed 'autogen/gentemplates/gen.go'
[   41s] + go build ./cmd/traefik
[  142s] # github.com/containous/traefik/autogen/genstatic
[  142s] runtime: out of memory: cannot allocate 368640-byte block (43350163456 in use)
[  142s] fatal error: out of memory
[  142s]
[  142s] runtime stack:
[  142s] runtime.throw(0xca9822, 0xd)
[  142s]    /usr/lib64/go/1.11/src/runtime/panic.go:608 +0x72
[  142s] runtime.largeAlloc(0x582c0, 0x450101, 0x7f256d242f70)
[  142s]    /usr/lib64/go/1.11/src/runtime/malloc.go:1021 +0x166
[  142s] runtime.mallocgc.func1()
[  142s]    /usr/lib64/go/1.11/src/runtime/malloc.go:914 +0x46
[  142s] runtime.systemstack(0x0)
[  142s]    /usr/lib64/go/1.11/src/runtime/asm_amd64.s:351 +0x66
[  142s] runtime.mstart()
[  142s]    /usr/lib64/go/1.11/src/runtime/proc.go:1229
[  142s]
[  142s] goroutine 37 [running]:
[  142s] runtime.systemstack_switch()
[  142s]    /usr/lib64/go/1.11/src/runtime/asm_amd64.s:311 fp=0xc6ad4e1f30 sp=0xc6ad4e1f28 pc=0x455e50
[  142s] runtime.mallocgc(0x582c0, 0xc619e0, 0xffffff000008e801, 0xc111a9ea80)
[  142s]    /usr/lib64/go/1.11/src/runtime/malloc.go:913 +0x896 fp=0xc6ad4e1fd0 sp=0xc6ad4e1f30 pc=0x40bb26
[  142s] runtime.makeslice(0xc619e0, 0x0, 0x582c, 0xca17f64000, 0x0, 0x582d)
[  142s]    /usr/lib64/go/1.11/src/runtime/slice.go:70 +0x77 fp=0xc6ad4e2000 sp=0xc6ad4e1fd0 pc=0x43f497
[  142s] cmd/compile/internal/ssa.(*regAllocState).computeLive(0xc0ac5ae780)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/ssa/regalloc.go:2464 +0x15ef fp=0xc6ad4e2318 sp=0xc6ad4e2000 pc=0x62ec9f
[  142s] cmd/compile/internal/ssa.(*regAllocState).init(0xc0ac5ae780, 0xc193fadce0)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/ssa/regalloc.go:675 +0x6ee fp=0xc6ad4e2400 sp=0xc6ad4e2318 pc=0x62002e
[  142s] cmd/compile/internal/ssa.regalloc(0xc193fadce0)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/ssa/regalloc.go:144 +0x4a fp=0xc6ad4e2428 sp=0xc6ad4e2400 pc=0x61db8a
[  142s] cmd/compile/internal/ssa.Compile(0xc193fadce0)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/ssa/compile.go:70 +0x30e fp=0xc6ad4e5e18 sp=0xc6ad4e2428 pc=0x5dd6de
[  142s] cmd/compile/internal/gc.buildssa(0xc03d0d78c0, 0x0, 0x0)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/gc/ssa.go:211 +0xab0 fp=0xc6ad4e5f30 sp=0xc6ad4e5e18 pc=0xb35960
[  142s] cmd/compile/internal/gc.compileSSA(0xc03d0d78c0, 0x0)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/gc/pgen.go:259 +0x39 fp=0xc6ad4e5f98 sp=0xc6ad4e5f30 pc=0xb027b9
[  142s] cmd/compile/internal/gc.compileFunctions.func2(0xc0a2ec2900, 0xc0a2ebc1c0, 0x0)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/gc/pgen.go:323 +0x49 fp=0xc6ad4e5fc8 sp=0xc6ad4e5f98 pc=0xbb7ac9
[  142s] runtime.goexit()
[  142s]    /usr/lib64/go/1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc6ad4e5fd0 sp=0xc6ad4e5fc8 pc=0x457db1
[  142s] created by cmd/compile/internal/gc.compileFunctions
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/gc/pgen.go:321 +0x11a
[  142s]
[  142s] goroutine 1 [semacquire, 1 minutes]:
[  142s] sync.runtime_Semacquire(0xc0a2ebc1c8)
[  142s]    /usr/lib64/go/1.11/src/runtime/sema.go:56 +0x39
[  142s] sync.(*WaitGroup).Wait(0xc0a2ebc1c0)
[  142s]    /usr/lib64/go/1.11/src/sync/waitgroup.go:130 +0x64
[  142s] cmd/compile/internal/gc.compileFunctions()
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/gc/pgen.go:333 +0x1c3
[  142s] cmd/compile/internal/gc.Main(0xcc41d0)
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/internal/gc/main.go:651 +0x276d
[  142s] main.main()
[  142s]    /usr/lib64/go/1.11/src/cmd/compile/main.go:51 +0x96
[  142s] error: Bad exit status from /var/tmp/rpm-tmp.0oTh4Y (%build)
[  142s]
[  142s]
[  142s] RPM build errors:
[  142s]     Bad exit status from /var/tmp/rpm-tmp.0oTh4Y (%build)
[  142s]
[  142s] skyrim failed "build traefik.spec" at Fri Jan 11 18:32:56 UTC 2019.
[  142s]
 
The buildroot was: /var/tmp/build-root/openSUSE_Tumbleweed-x86_64
```

I've tried that to systems with a lot of RAM, e.g. more than 64GB DDR4 and it stills complains about the same error. Could please let me know how to handle this situation?

**Comment by ldez** [comment]
https://github.com/containous/traefik/blob/master/webui/readme.md#how-to-build-only-for-frontends-developer

**Comment by ldez** [comment]
A way to build Traefik without git:

```bash
## Install Go

####
## Setup Go
####

export GOPATH=$HOME/go; mkdir $GOPATH
export GOBIN=$GOPATH/bin; mkdir $GOBIN
export PATH=$PATH:$GOBIN

####
## download sources
####

wget --output-document=go-bindata.tar.gz https://github.com/containous/go-bindata/archive/v1.0.0.tar.gz
wget https://github.com/containous/traefik/releases/download/v1.7.7/traefik-v1.7.7.src.tar.gz

####
## go-bindata
####

# IMPORTANT this path cannot be changed
mkdir -p $GOPATH/src/github.com/containous/go-bindata/

tar -xzf go-bindata.tar.gz -C $GOPATH/src/github.com/containous/
rm go-bindata.tar.gz
mv $GOPATH/src/github.com/containous/go-bindata-1.0.0 $GOPATH/src/github.com/containous/go-bindata/

####
## traefik
####

# IMPORTANT this path cannot be changed
mkdir -p $GOPATH/src/github.com/containous/traefik/

tar -xzf traefik-v1.7.7.src.tar.gz -C $GOPATH/src/github.com/containous/traefik/
rm traefik-v1.7.7.src.tar.gz

####
## go-bindata
####

cd $GOPATH/src/github.com/containous/go-bindata/
go install


####
## traefik
####
cd $GOPATH/src/github.com/containous/traefik
go generate
go build ./cmd/traefik
```
