### ISSUE TITLE
no such file or directory "zoneinfo.zip"

### ISSUE THREAD

**Issue by xianyuLuo** [containous/traefik#4404]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Apply for a certificate using ACME

### What did you see instead?

```
level=error msg="Error in Go routine: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.7
```

**Comment by ldez** [comment]
@xianyuLuo could you give more information:
- [ ] full logs
- [ ] configuration

**Comment by xianyuLuo** [comment]
run in Kubernetes
image is traefik:v1.7.7
traefik.toml is as follows
```
defaultEntryPoints = ["http","https"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"

      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [acme]
      storage = "acme.json"
      entryPoint = "https"
    [acme.dnsChallenge]
      provider = "alidns"
      delayBeforeCheck = 10
      resolvers = ["ns1.alidns.com", "dns19.hichina.com"]  # 必须配置为阿里云的dns 见https://community.letsencrypt.org/t/caa-servfail-changes/38298
    [[acme.domains]]
      main = "*.xianyuluo.com"
```

**Comment by ldez** [comment]
After some investigation, I think it's related to Alibaba and the Traefik image (`FROM SCRATCH`).

Alibaba use:
```
time.LoadLocation("GMT")
```

This cannot works inside a `FROM SCRATCH` container, so I recommend to use the Alpine version of Traefik (`traefik:v1.7-alpine`)

**Comment by xianyuLuo** [comment]
OK , let me try traefik:v1.7-alpine
Thanks

**Comment by xianyuLuo** [comment]
It's good

**Comment by milewski** [comment]
Hey its not working for me... Im running `image: traefik:1.7.9-alpine`

```
time="2019-03-03T16:26:34Z" level=error msg="Error in Go routine: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory"
time="2019-03-03T16:26:34Z" level=error msg="Stack: goroutine 53 [running]:\nruntime/debug.Stack(0x271eb94, 0x17, 0xc00090f270)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/containous/traefik/safe.defaultRecoverGoroutine(0x221e200, 0xc00090f260)\n\t/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89\ngithub.com/containous/traefik/safe.GoWithRecover.func1.1(0x27d7ec8)\n\t/go/src/github.com/containous/traefik/safe/routine.go:139 +0x57\npanic(0x221e200, 0xc00090f260)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils.GetTimeInFormatISO8601(0x2200c20, 0xc0005561e0)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils/utils.go:60 +0x140\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.completeRpcSignParams(0x2a75ba0, 0xc000554310, 0x2a54ec0, 0xc000182370, 0xc00004c033, 0xb, 0x0, 0x0)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/rpc_signature_composer.go:47 +0x1de\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.signRpcRequest(0x2a75ba0, 0xc000554310, 0x2a54ec0, 0xc000182370, 0xc00004c033, 0xb, 0x2a77340, 0x3)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/rpc_signature_composer.go:26 +0x73\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.Sign(0x2a75ba0, 0xc000554310, 0x2a54ec0, 0xc000182370, 0xc00004c033, 0xb, 0x8, 0x0)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signer.go:87 +0x273\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.buildHttpRequest(0x2a75ba0, 0xc000554310, 0x2a54ec0, 0xc000182370, 0xc00004c033, 0xb, 0xc000556240, 0x20be640, 0x8)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:287 +0x84\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc00054d9a0, 0x2a75ba0, 0xc000554310, 0x2a55a60, 0xc00019d810, 0x0, 0x0, 0x2200c01, 0xc00017f800)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:239 +0x3d2\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(0xc00054d9a0, 0x2a75ba0, 0xc000554310, 0x2a55a60, 0xc00019d810, 0x1, 0x273faf7)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:151 +0x5b\ngithub.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns.(*Client).DescribeDomains(0xc00054d9a0, 0xc000554310, 0x1, 0xe88cb684d9c0142d, 0xcd7bd0a9d50f8f27)\n\t/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/describe_domains.go:27 +0x98\ngithub.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns.(*DNSProvider).getHostedZone(0xc0005711f0, 0xc000579e60, 0x12, 0x57, 0xc0004c7c50, 0x23, 0xc0004c7c20, 0x2b, 0xc0008cb078)\n\t/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns/alidns.go:146 +0xcc\ngithub.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns.(*DNSProvider).Present(0xc0005711f0, 0xc000579e60, 0x12, 0xc0004c7b00, 0x2b, 0xc0008634a0, 0x57, 0xc000550d60, 0x3)\n\t/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns/alidns.go:98 +0xba\ngithub.com/containous/traefik/vendor/github.com/xenolf/lego/challenge/dns01.(*Challenge).PreSolve(0xc0006e4300, 0xc000550d63, 0x7, 0x0, 0xed4172f47, 0x0, 0xc000550d60, 0x3, 0xc000579e60, 0x12, ...)\n\t/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/challenge/dns01/dns_challenge.go:94 +0x2a8\ngithub.com/containous/traefik/vendor/github.com/xenolf/lego/challenge/resolver.parallelSolve(0xc00000c9a0, 0x1, 0x1, 0xc0005561b0)\n\t/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/challenge/resolver/prober.go:135 +0x102\ngithub.com/containous/traefik/vendor/github.com/xenolf/lego/challenge/resolver.(*Prober).Solve(0xc000182350, 0xc0005542a0, 0x1, 0x1, 0x14, 0xc000128700)\n\t/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/challenge/resolver/prober.go:84 +0x35e\ngithub.com/containous/traefik/vendor/github.com/xenolf/lego/certificate.(*Certifier).Obtain(0xc0003fab40, 0xc0002d8350, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1, 0x1, ...)\n\t/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/certificate/certificates.go:114 +0x36e\ngithub.com/containous/traefik/provider/acme.(*Provider).resolveCertificate(0xc0001c2bd0, 0xc000145bc0, 0x14, 0x0, 0x0, 0x0, 0x1054e01, 0x0, 0x0, 0x0)\n\t/go/src/github.com/containous/traefik/provider/acme/provider.go:421 +0xb22\ngithub.com/containous/traefik/provider/acme.(*Provider).Provide.func1()\n\t/go/src/github.com/containous/traefik/provider/acme/provider.go:188 +0x72\ngithub.com/containous/traefik/safe.GoWithRecover.func1(0x27d7ec8, 0xc000338580)\n\t/go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d\ncreated by github.com/containous/traefik/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/safe/routine.go:136 +0x49\n"
```

**Comment by ldez** [comment]
FYI, since Traefik v1.7.10 the official alpine base image contains zoneinfo.zip.
