### ISSUE TITLE
Update of consul from 1.4.0 to 1.4.1 breaks catalog watch

### ISSUE THREAD

**Issue by zyclonite** [containous/traefik#4425]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

upgrade consul from 1.4.0 to 1.4.1
traefik instance configured for consul catalog

### What did you expect to see?

traefik working as before, showing all frontends and backends correctly

### What did you see instead?

no frontend or backend discovered at all

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2019-01-24T10:17:34Z" level=error msg="Failed to retrieve health checks" error="time: invalid duration "
time="2019-01-24T10:17:34Z" level=error msg="Error in Go routine: send on closed channel"
time="2019-01-24T10:17:34Z" level=error msg="Stack: goroutine 3580 [running]:\nruntime/debug.Stack(0x26c79d0, 0x17, 0xc0004ee810)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/containous/traefik/safe.defaultRecoverGoroutine(0x22432a0, 0x29b95e0)\n\t/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89\ngithub.com/containous/traefik/safe.GoWithRecover.func1.1(0x277fa88)\n\t/go/src/github.com/containous/traefik/safe/routine.go:139 +0x57\npanic(0x22432a0, 0x29b95e0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/containous/traefik/provider/consulcatalog.(*Provider).watchCatalogServices.func1()\n\t/go/src/github.com/containous/traefik/provider/consulcatalog/consul_catalog.go:261 +0x7dc\ngithub.com/containous/traefik/safe.GoWithRecover.func1(0x277fa88, 0xc000342a80)\n\t/go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d\ncreated by github.com/containous/traefik/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/safe/routine.go:136 +0x49\n"
time="2019-01-24T10:17:34Z" level=error msg="Consul connection error time: invalid duration , retrying in 3.95327303s"
```

### possible causes

* looks like the traefik consul api lib is quite old (1.0.6)
* consul changed the health definition from api.ReadableDuration to time.Duration
* when the service health is queried it now returns not an empty definition structure any more but fields which are set to an empty string

**Comment by zyclonite** [comment]
is identified and looks like getting fixed on consul client side https://github.com/hashicorp/consul/issues/5270
