### ISSUE TITLE
A frontend route without a rule (or empty rule) causes a crash when traefik starts

### ISSUE THREAD

**Issue by marccampbell** [containous/traefik#453]
I have the following keys in my consul store:

```
/traefik/backends/app/servers/server1/url
/traefik/backends/app/servers/server1/weight

/traefik/frontends/app/backend
/traefik/frontends/app/entrypoint
/traefik/frontends/app/priority
/traefik/frontends/app/routes/host/rules
```

(that last key should be named `rule`, not `rules`.  When starting traefik in with this store, it crashes with:

```go
2016/06/12 02:16:21 routine.go:68: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/containous/traefik/safe.defaultRecoverGoroutine(0xe08c60, 0xc82000e0e0)
	/go/src/github.com/containous/traefik/safe/routine.go:69 +0x81
github.com/containous/traefik/safe.GoWithRecover.func1.1(0x1186788)
	/go/src/github.com/containous/traefik/safe/routine.go:60 +0x4e
panic(0xe08c60, 0xc82000e0e0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
main.getRoute(0xc8204467c0, 0xc8204467e0, 0x0, 0x0)
	/go/src/github.com/containous/traefik/server.go:589 +0x4b7
main.(*Server).loadConfig(0xc820362d00, 0xc82043f560, 0xa, 0x0, 0xc8202ec600, 0x1b, 0xc8202ec660, 0x1c, 0xf8bc78, 0x5, ...)
	/go/src/github.com/containous/traefik/server.go:400 +0x1004
main.(*Server).listenConfigurations(0xc820362d00, 0xc820364460)
	/go/src/github.com/containous/traefik/server.go:195 +0x60c
main.(*Server).Start.func2(0xc820364460)
	/go/src/github.com/containous/traefik/server.go:93 +0x2a
github.com/containous/traefik/safe.(*Pool).Go.func1()
	/go/src/github.com/containous/traefik/safe/routine.go:31 +0x41
github.com/containous/traefik/safe.GoWithRecover.func1(0x1186788, 0xc82035b8c0)
	/go/src/github.com/containous/traefik/safe/routine.go:63 +0x44
created by github.com/containous/traefik/safe.GoWithRecover
	/go/src/github.com/containous/traefik/safe/routine.go:64 +0x3f2016/06/12 02:16:21 routine.go:68: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/containous/traefik/safe.defaultRecoverGoroutine(0xe08c60, 0xc82000e0e0)
	/go/src/github.com/containous/traefik/safe/routine.go:69 +0x81
github.com/containous/traefik/safe.GoWithRecover.func1.1(0x1186788)
	/go/src/github.com/containous/traefik/safe/routine.go:60 +0x4e
panic(0xe08c60, 0xc82000e0e0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
main.getRoute(0xc8204467c0, 0xc8204467e0, 0x0, 0x0)
	/go/src/github.com/containous/traefik/server.go:589 +0x4b7
main.(*Server).loadConfig(0xc820362d00, 0xc82043f560, 0xa, 0x0, 0xc8202ec600, 0x1b, 0xc8202ec660, 0x1c, 0xf8bc78, 0x5, ...)
	/go/src/github.com/containous/traefik/server.go:400 +0x1004
main.(*Server).listenConfigurations(0xc820362d00, 0xc820364460)
	/go/src/github.com/containous/traefik/server.go:195 +0x60c
main.(*Server).Start.func2(0xc820364460)
	/go/src/github.com/containous/traefik/server.go:93 +0x2a
github.com/containous/traefik/safe.(*Pool).Go.func1()
	/go/src/github.com/containous/traefik/safe/routine.go:31 +0x41
github.com/containous/traefik/safe.GoWithRecover.func1(0x1186788, 0xc82035b8c0)
	/go/src/github.com/containous/traefik/safe/routine.go:63 +0x44
created by github.com/containous/traefik/safe.GoWithRecover
	/go/src/github.com/containous/traefik/safe/routine.go:64 +0x3f
```

Renaming this `rules` key to `rule` allows traefik to start.

Expected behavior:
I'd expect an error to be logged and the rule (or frontend) not be applied.  I'm not yet familiar enough with traefik to suggest the right behavior, but I think a log message would be useful in this scenario.

**Comment by vdemeester** [comment]
hum at least we should not panic :sweat:
