### ISSUE TITLE
Go Panic when log: is enable with out log level

### ISSUE THREAD

**Issue by ZetaPhoenix** [containous/traefik#5548]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Accidently left `log:` enabled after commenting out log level: debug after ending debug session.

traefik.yml
```yml
log:
# DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
#  level: DEBUG
```

### What did you expect to see?

Default log level

### What did you see instead?

Traefik failed to run. See below for log output

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:25:50Z
OS/Arch:      linux/arm

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true
  insecure: true
#  debug: true

log:
# DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
#  level: DEBUG
....
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
goroutine 1 [running]:
github.com/containous/traefik/v2/pkg/config/file.decodeRaw(0x557ee40, 0x1747868, 0x57060e0, 0x15, 0x55206c0, 0xd, 0x18)
	/go/src/github.com/containous/traefik/pkg/config/file/raw_node.go:79 +0x978
github.com/containous/traefik/v2/pkg/config/file.decodeRawToNode(0x57060e0, 0x1a96a71, 0x7, 0x55206c0, 0xd, 0x18, 0x0, 0x0, 0x30)
	/go/src/github.com/containous/traefik/pkg/config/file/raw_node.go:18 +0xdc
github.com/containous/traefik/v2/pkg/config/file.decodeFileToNode(0x576e7d0, 0xc, 0x55206c0, 0xd, 0x18, 0x5, 0x5522280, 0x576e7d0)
	/go/src/github.com/containous/traefik/pkg/config/file/file_node.go:43 +0x168
github.com/containous/traefik/v2/pkg/config/file.Decode(0x576e7d0, 0xc, 0x185b480, 0x5549300, 0x3, 0x3)
	/go/src/github.com/containous/traefik/pkg/config/file/file.go:20 +0x40
github.com/containous/traefik/v2/pkg/cli.loadConfigFiles(0x0, 0x0, 0x185b480, 0x5549300, 0x318c420, 0x5696c00, 0x0, 0x0)
	/go/src/github.com/containous/traefik/pkg/cli/loader_file.go:81 +0xc4
github.com/containous/traefik/v2/pkg/cli.(*FileLoader).Load(0x54f4f30, 0x540c050, 0x0, 0x0, 0x5549380, 0x1bd64, 0x5549400, 0x40)
	/go/src/github.com/containous/traefik/pkg/cli/loader_file.go:44 +0xec
github.com/containous/traefik/v2/pkg/cli.run(0x5549380, 0x540c050, 0x0, 0x0, 0x38, 0x5549400)
	/go/src/github.com/containous/traefik/pkg/cli/commands.go:108 +0xf0
github.com/containous/traefik/v2/pkg/cli.execute(0x5549380, 0x540c050, 0x2, 0x2, 0x14e01, 0x54480b0, 0x0)
	/go/src/github.com/containous/traefik/pkg/cli/commands.go:64 +0x328
github.com/containous/traefik/v2/pkg/cli.Execute(...)
	/go/src/github.com/containous/traefik/pkg/cli/commands.go:40
main.main()
	/go/src/github.com/containous/traefik/cmd/traefik/traefik.go:65 +0x3e4
panic: Unsupported type: invalid
```

**Comment by ZetaPhoenix** [comment]
Feel free to close this if this is expected behavior. I find it strange that Traefik would crash instead of assuming default levels.

**Comment by ldez** [comment]
Hello,

It's not a valid YAML syntax, so yes this kind of error can produce some unexpected behavior.

**Comment by ldez** [comment]
In #5548, I remove the panic but this kind of syntax will still stop Traefik.
