### ISSUE TITLE
Mirroring does not work with a body in the request. (e.g.: POST request)

### ISSUE THREAD

**Issue by cyrilgdn** [containous/traefik#5893]
I tried to configure a mirroring with the new [mirroring feature](https://docs.traefik.io/routing/services/#mirroring-service) but it seems to work only for `GET` requests (or at least for requests without body)

How to reproduce
-----------------------
I've created a little Go HTTP server which just prints the body:
```go
package main

import (
        "flag"
        "fmt"
        "io/ioutil"
        "log"
        "net/http"
)

func main() {
        var port = flag.Int("port", 8888, "port to listen on")
        flag.Parse()

        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                fmt.Fprintf(w, "Hi there o/")
                body, err := ioutil.ReadAll(r.Body)
                if err != nil {
                        panic(err)
                }
                fmt.Printf("body: %s\n", body)

        })
        log.Fatal(http.ListenAndServe(fmt.Sprintf(":%d", *port), nil))

```
and start it twice on 2 different ports (`6666` and `7777`)

I have the following file provider configuration: (if you run Traefik in Docker, you'll need to replace `localhost` with your computer IP address)
```yaml
http:
  routers:
    test:
      rule: PathPrefix(`/`)
      service: mirror-test

  services:
    mirror-test:
     mirroring:
       service: test
       mirrors:
           - name: test-mirror
             percent: 100

    test:
      loadBalancer:
        servers:
            - url: http://localhost:7777

    test-mirror:
      loadBalancer:
        servers:
            - url: http://localhost:6666
```

Then I run Traefik with Docker:
```
$ docker run --rm -p 8888:80 -v $(pwd)/mirror.yml:/srv/mirror.yml traefik:v2.0.5 --providers.file.filename=/srv/mirror.yml --log.level=debug
```

But I also tried by building Traefik on the `master` branch and running
```
$ go run ./cmd/traefik --entrypoints.http.address=localhost:8888 -providers.file.filename=mirror.yml --log.level=debug
```

Then a simple POST with curl:
```
$ curl -X POST http://localhost:8888/ -d '{"test": "test"}'
```

The Go server listening on 777  prints:
```
body: {"test": "test"}
```
but the mirror panics as it receives an empty body with a non-zero content length:
```
2019/11/25 19:39:12 http: panic serving [::1]:47150: unexpected EOF
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc00015a0a0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x6a9e40, 0xc00008a060)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.main.func1(0x76fcc0, 0xc0001300e0, 0xc000188000)
	/tmp/main.go:19 +0x18f
net/http.HandlerFunc.ServeHTTP(0x71fc98, 0x76fcc0, 0xc0001300e0, 0xc000188000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x944ca0, 0x76fcc0, 0xc0001300e0, 0xc000188000)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0000e0000, 0x76fcc0, 0xc0001300e0, 0xc000188000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00015a0a0, 0x770280, 0xc00016c0c0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

Traefik logs for this query:
```
DEBU[2019-11-25T19:39:12+01:00] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"16\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.0\"],\"X-Forwarded-Host\":[\"localhost:8888\"],\"X-Forwarded-Port\":[\"8888\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"zeratul\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":16,\"TransferEncoding\":null,\"Host\":\"localhost:8888\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:46308\",\"RequestURI\":\"/\",\"TLS\":null}"
DEBU[2019-11-25T19:39:12+01:00] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"16\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.0\"],\"X-Forwarded-Host\":[\"localhost:8888\"],\"X-Forwarded-Port\":[\"8888\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"zeratul\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":16,\"TransferEncoding\":null,\"Host\":\"localhost:8888\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:46308\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://localhost:7777"
DEBU[2019-11-25T19:39:12+01:00] vulcand/oxy/roundrobin/rr: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"16\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.0\"],\"X-Forwarded-Host\":[\"localhost:8888\"],\"X-Forwarded-Port\":[\"8888\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"zeratul\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":16,\"TransferEncoding\":null,\"Host\":\"localhost:8888\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:46308\",\"RequestURI\":\"/\",\"TLS\":null}"
DEBU[2019-11-25T19:39:12+01:00] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"16\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.0\"],\"X-Forwarded-Host\":[\"localhost:8888\"],\"X-Forwarded-Port\":[\"8888\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"zeratul\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":16,\"TransferEncoding\":null,\"Host\":\"localhost:8888\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:46308\",\"RequestURI\":\"/\",\"TLS\":null}"
DEBU[2019-11-25T19:39:12+01:00] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"16\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.0\"],\"X-Forwarded-Host\":[\"localhost:8888\"],\"X-Forwarded-Port\":[\"8888\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"zeratul\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":16,\"TransferEncoding\":null,\"Host\":\"localhost:8888\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:46308\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://localhost:6666"
DEBU[2019-11-25T19:39:12+01:00] '502 Bad Gateway' caused by: readfrom tcp [::1]:47150->[::1]:6666: http: invalid Read on closed Body 
DEBU[2019-11-25T19:39:12+01:00] vulcand/oxy/roundrobin/rr: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"16\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.0\"],\"X-Forwarded-Host\":[\"localhost:8888\"],\"X-Forwarded-Port\":[\"8888\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"zeratul\"],\"X-Real-Ip\":[\"127.0.0.1\"]},\"ContentLength\":16,\"TransferEncoding\":null,\"Host\":\"localhost:8888\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"127.0.0.1:46308\",\"RequestURI\":\"/\",\"TLS\":null}"
```

We can see the following error:
**'502 Bad Gateway' caused by: readfrom tcp [::1]:47150->[::1]:6666: http: invalid Read on closed Body**

When processing the query for the mirror, the body is already closed so I quickly tried to applied the same fix than [the one applied for the retry middleware](https://github.com/containous/traefik/pull/1016/files) but it did not worked (and I don't get why :( )

(cc @juliens )

**Comment by mpl** [comment]
@cyrilgdn Hi. Could you please explain why a mirror would need to have access to the body, since it's not meant to reply to the request anyway?

**Comment by hoesler** [comment]
@mpl A use case I have is storing samples in a separate database. I don't care what is replied or if some requests fail.

**Comment by cyrilgdn** [comment]
> @cyrilgdn Hi. Could you please explain why a mirror would need to have access to the body, since it's not meant to reply to the request anyway?

Our use case is to test a new version of a service without releasing it. All requests to the production service are (would be) mirrored to this new service and we can check if it behaves correctly with the logs or by storing the response in a database.

And actually, you could ask this question for the GET too ? What's your point to create a mirror whatever the method since you'll not have the response :) ?

**Comment by mpl** [comment]
Yes, my question was not specifically about POST. But it does not matter as much because the Body is often (not always, as some people abuse the prototol that way) empty with GET.
And to answer your question, there are cases where having a mirror even without the Body is already useful. the mirror could be dedicated to access logging for example.
Anyway, now it's up to carefully reviewing #6080

**Comment by einali** [comment]
Hi everybody

We are using traefik as API gateway for grpc service(mostly AI related APIs).
We need to log very detail parameters of request and response(including their size in seconds for voice and char length  for text) on kafka queue

we had to patch traefik to supoort such use case.if  mirroring features works for gRPC we can discard our patch and use traefik out of the box version.
i thinks mirroring service for whole request is very reasonable.

its is possible in istio to use mirroring in gRPC  traffic:
[https://github.com/istio/istio/issues/10057](istio grpc mirroring test issue)

BTW: gRPC mirroring  needs request payload support and http2 streaming.
