### ISSUE TITLE
Provider connection error panic in operation

### ISSUE THREAD

**Issue by maxried** [containous/traefik#6024]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I use traefik with docker-compose. I accidentally defined a broken label like so:
```
    test:
        build: "test"
        container_name: "test"
        restart: "always"
        depends_on: 
            - "traefik"
        networks:
            test-frontend:
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.test-https.rule=Host(`test.example.com`)"
            - "traefik.http.routers.test-https.entrypoints=web-secure"
            - "traefik.http.routers.test-https.tls=true"
            - "traefik.http."
```

### What did you expect to see?

I expected traefik to warn me about my mistake and to safely ignore the tag.

### What did you see instead?

```Dec 13 12:10:40 www-neu traefik[11728]: time="2019-12-13T11:10:40Z" level=debug msg="Provider connection established with docker 19.03.5 (API 1.40)" providerName=docker
Dec 13 12:10:40 www-neu traefik[11728]: time="2019-12-13T11:10:40Z" level=error msg="Error in Go routine: runtime error: index out of range [0] with length 0"
Dec 13 12:10:40 www-neu traefik[11728]: time="2019-12-13T11:10:40Z" level=error msg="Stack: goroutine 62 [running]:\nruntime/debug.Stack(0xc00010c000, 0x2550df9, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x235a380, 0xc0007e5420)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:160 +0xb1\ngithub.com/containous/traefik/v2/pkg/safe.OperationWithRecover.func1.1(0xc000705d78)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:168 +0x56\npanic(0x235a380, 0xc0007e5420)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/containous/traefik/v2/pkg/config/parser.DecodeToNode(0xc0007a7e30, 0x252f8bb, 0x7, 0xc0007053a0, 0x2, 0x2, 0x10, 0x21fd9e0, 0x29f5b01)\n\t/go/src/github.com/containous/traefik/pkg/config/parser/labels_decode.go:24 +0x6ec\ngithub.com/containous/traefik/v2/pkg/config/parser.Decode(0xc0007a7e30, 0x21158e0, 0xc00095db40, 0x252f8bb, 0x7, 0xc0007053a0, 0x2, 0x2, 0x75ffba, 0x241de40)\n\t/go/src/github.com/containous/traefik/pkg/config/parser/parser.go:11 +0x6d\ngithub.com/containous/traefik/v2/pkg/config/label.DecodeConfiguration(0xc0007a7e30, 0xc000290510, 0x29f5b60, 0xc0003e2a80)\n\t/go/src/github.com/containous/traefik/pkg/config/label/label.go:16 +0xfb\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).buildConfiguration(0xc000318c40, 0x29ac080, 0xc0001f6c30, 0xc000a5a000, 0x6, 0x8, 0x6)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/config.go:31 +0x326\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).Provide.func1.1(0x0, 0x0)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/docker.go:193 +0x657\ngithub.com/containous/traefik/v2/pkg/safe.OperationWithRecover.func1(0x0, 0x0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:172 +0x6c\ngithub.com/cenkalti/backoff/v3.RetryNotify(0xc0002ba840, 0x296a180, 0xc0000c9000, 0xc000705ef0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.0.0/retry.go:37 +0xb8\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).Provide.func1(0x29abfc0, 0xc00012c680)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/docker.go:293 +0x2d6\ngithub.com/containous/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:63 +0x84\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x262c6e0, 0xc0000c8fe0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:153 +0x57\ncreated by github.com/containous/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:147 +0x49\n"
Dec 13 12:10:40 www-neu traefik[11728]: time="2019-12-13T11:10:40Z" level=error msg="Provider connection error panic in operation: %!s(<nil>), retrying in 14.398432638s" providerName=docker
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.1
Codename:     cantal
Go version:   go1.13.5
Built:        2019-12-12T19:01:37Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
services: 
    traefik:
        image: "traefik:latest"
        container_name: "traefik"
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.endpoint=tcp://docker-host:2376"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web-secure.address=:443"
            - "--accesslog=true"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        networks:
            test-frontend:
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.redirect-catchall.redirectregex.regex=.*"
            - "traefik.http.middlewares.redirect-catchall.redirectregex.replacement=http://example.com/"
            - "traefik.http.routers.catchall-http.rule=PathPrefix(`/`)"
            - "traefik.http.routers.catchall-http.middlewares=redirect-catchall"
            - "traefik.http.routers.catchall-http.priority=1"
            - "traefik.http.routers.catchall-http.entrypoints=web"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

See above.

**Comment by traefiker** [comment]
Closed by #6028.
