### ISSUE TITLE
Upgraded from 1.6.6 to 1.7.0 caused ECS providers to be retrieved

### ISSUE THREAD

**Issue by kave** [containous/traefik#6066]
### What did you do?
Upgraded from 1.6.6 to 1.7.0, and it is causing an exception when polling the ECS API. 
to be thorough i tried every single minor version 1.7.0 -> 1.7.20. No solution yet

### What did you expect to see?

I expected to see my ecs providers display

### What did you see instead?

<img width="1186" alt="Traefik" src="https://user-images.githubusercontent.com/254877/71120736-07128580-21ab-11ea-8032-d9712aa7fd77.png">

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
  users = ["credentials"]

[ping]
[api]
  dashboard = true
  [api.statistics]
    recentErrors = 10

logLevel = "INFO"

[traefikLog]
  format   = "json"

[ecs]
clusters = ["development", "development2"]
watch = true
domain = "example.com"
autoDiscoverClusters = false
refreshSeconds = 15
exposedByDefault = false
region = "us-east-2"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```

{"level":"error","msg":"Error in Go routine: runtime error: invalid memory address or nil pointer dereference","time":"2019-12-18T20:26:19Z"}
{"level":"error","msg":"Stack: goroutine 70 [running]:\nruntime/debug.Stack(0x26cb820, 0x17, 0xc0012ee0f0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/containous/traefik/safe.defaultRecoverGoroutine(0x2246600, 0x4603250)\n\t/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89\ngithub.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc00101be18)\n\t/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56\npanic(0x2246600, 0x4603250)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/containous/traefik/provider/ecs.(*Provider).listInstances(0xc0004432b0, 0x29eaee0, 0xc000087400, 0xc000423330, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/containous/traefik/provider/ecs/ecs.go:322 +0xe62\ngithub.com/containous/traefik/provider/ecs.(*Provider).loadECSConfig(0xc0004432b0, 0x29eaee0, 0xc000087400, 0xc000423330, 0x2030e80, 0x203000, 0x203000)\n\t/go/src/github.com/containous/traefik/provider/ecs/ecs.go:426 +0x4d\ngithub.com/containous/traefik/provider/ecs.(*Provider).Provide.func2.2(0x0, 0x0)\n\t/go/src/github.com/containous/traefik/provider/ecs/ecs.go:144 +0xb7\ngithub.com/containous/traefik/safe.OperationWithRecover.func1(0x0, 0x0)\n\t/go/src/github.com/containous/traefik/safe/routine.go:160 +0x62\ngithub.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc0004231d0, 0x29c9760, 0xc0004231f0, 0x2783850, 0xc0004231c0, 0xc0008b9980)\n\t/go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37 +0xa2\ngithub.com/containous/traefik/provider/ecs.(*Provider).Provide.func2(0xc0000884d0)\n\t/go/src/github.com/containous/traefik/provider/ecs/ecs.go:181 +0x1c0\ngithub.com/containous/traefik/safe.(*Pool).Go.func1()\n\t/go/src/github.com/containous/traefik/safe/routine.go:78 +0x37\ngithub.com/containous/traefik/safe.GoWithRecover.func1(0x2783a68, 0xc000036660)\n\t/go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d\ncreated by github.com/containous/traefik/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/safe/routine.go:136 +0x49\n","time":"2019-12-18T20:26:19Z"}
{"level":"error","msg":"Provider connection error panic in operation: %!s(\u003cnil\u003e), retrying in 543.930941ms","time":"2019-12-18T20:26:19Z"}

```

```
Stack: goroutine 70 [running]:
runtime/debug.Stack(0x26cb820, 0x17, 0xc0012ee0f0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x2246600, 0x4603250)
	/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89
github.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc00101be18)
	/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56
panic(0x2246600, 0x4603250)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/containous/traefik/provider/ecs.(*Provider).listInstances(0xc0004432b0, 0x29eaee0, 0xc000087400, 0xc000423330, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/containous/traefik/provider/ecs/ecs.go:322 +0xe62
github.com/containous/traefik/provider/ecs.(*Provider).loadECSConfig(0xc0004432b0, 0x29eaee0, 0xc000087400, 0xc000423330, 0x2030e80, 0x203000, 0x203000)
	/go/src/github.com/containous/traefik/provider/ecs/ecs.go:426 +0x4d
github.com/containous/traefik/provider/ecs.(*Provider).Provide.func2.2(0x0, 0x0)
	/go/src/github.com/containous/traefik/provider/ecs/ecs.go:144 +0xb7
github.com/containous/traefik/safe.OperationWithRecover.func1(0x0, 0x0)
	/go/src/github.com/containous/traefik/safe/routine.go:160 +0x62
github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc0004231d0, 0x29c9760, 0xc0004231f0, 0x2783850, 0xc0004231c0, 0xc0008b9980)
	/go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37 +0xa2
github.com/containous/traefik/provider/ecs.(*Provider).Provide.func2(0xc0000884d0)
	/go/src/github.com/containous/traefik/provider/ecs/ecs.go:181 +0x1c0
github.com/containous/traefik/safe.(*Pool).Go.func1()
	/go/src/github.com/containous/traefik/safe/routine.go:78 +0x37
github.com/containous/traefik/safe.GoWithRecover.func1(0x2783a68, 0xc000036660)
	/go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
created by github.com/containous/traefik/safe.GoWithRecover
	/go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
```

**Comment by dtomcej** [comment]
@kave, the error in your log is referencing this line:

https://github.com/containous/traefik/blob/v1.7/provider/ecs/ecs.go#L322

`privateIP: aws.StringValue(containerInstance.PrivateIpAddress),`

Does one of your containerInstances not have a privateIP address?

**Comment by kave** [comment]
@dtomcej you are absolutely right. i forgot to mention in the original issue post that we were using traefik to discover frontend/backends from 2 clusters. It was the 2nd cluster that was misconfigured and had some containers in a restart cycles. I removed the bad cluster and everything worked. i'll focus on the aws configurations now instead of traefik. 
Thanks!
