### ISSUE TITLE
docker: Error in Go routine: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rjsocha** [containous/traefik#6197]
### What did you do?

Hi,
I don't know if this know. I had catch this  by accident (syntax error in cli).

too short traefik related label `traefik.http.services.test`

### What did you expect to see?

A simple error message.

### What did you see instead?

panic

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.1.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

When playing with traefik started by this command:

```bash
docker pull traefik:2.1
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
  traefik:2.1 \
  --providers.docker \
  --providers.docker.exposedbydefault=false \
  --entrypoints.http.address=:80 \
  --entrypoints.https.address=:443
```

I started this command:
```bash
docker run --rm \
  -l 'traefik.http.routers.test.rule=Host(`test`)' \
  -l traefik.http.services.test \
  -l traefik.enable=true \
  containous/whoami
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I was flooded by this error log:
```
time="2020-01-19T00:10:15Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2020-01-19T00:10:15Z" level=error msg="Stack: goroutine 38 [running]:\nruntime/debug.Stack(0xc0000e8000, 0x25581e1, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x210c480, 0x3fbcdb0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:160 +0xb1\ngithub.com/containous/traefik/v2/pkg/safe.OperationWithRecover.func1.1(0xc00022fd78)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:168 +0x56\npanic(0x210c480, 0x3fbcdb0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).addServer(0xc00014d2d0, 0x29b4960, 0xc00067cc00, 0xc000616300, 0x40, 0xc000647535, 0xb, 0xc000647535, 0xb, 0xc00067c4b0, ...)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/config.go:184 +0x116\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).buildServiceConfiguration(0xc00014d2d0, 0x29b4960, 0xc00067cab0, 0xc000616300, 0x40, 0xc000647535, 0xb, 0xc000647535, 0xb, 0xc00067c4b0, ...)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/config.go:113 +0x1dd\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).buildConfiguration(0xc00014d2d0, 0x29b4960, 0xc0001f2de0, 0xc000653440, 0x2, 0x2, 0x2)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/config.go:52 +0x5e0\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).Provide.func1.1(0x0, 0x0)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/docker.go:193 +0x657\ngithub.com/containous/traefik/v2/pkg/safe.OperationWithRecover.func1(0x0, 0x0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:172 +0x6c\ngithub.com/cenkalti/backoff/v3.RetryNotify(0xc0001f7920, 0x29729e0, 0xc0003f89a0, 0xc00022fef0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.0.0/retry.go:37 +0xb8\ngithub.com/containous/traefik/v2/pkg/provider/docker.(*Provider).Provide.func1(0x29b48a0, 0xc0003d2d40)\n\t/go/src/github.com/containous/traefik/pkg/provider/docker/docker.go:293 +0x2d6\ngithub.com/containous/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:63 +0x84\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x2633df8, 0xc0003f8980)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:153 +0x57\ncreated by github.com/containous/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:147 +0x49\n"
time="2020-01-19T00:10:15Z" level=error msg="Provider connection error panic in operation: %!s(<nil>), retrying in 10.183428799s" providerName=docker
```

**Comment by traefiker** [comment]
Closed by #6198.
