### ISSUE TITLE
traefik 2.1.9 Error in Go routine: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhengqisong** [containous/traefik#6587]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
version: 2.1.9
kubernetes-crd

config:
```
[entrypoints]
  [entrypoints.http]
    Address = "xxx"
    [entrypoints.http.transport]
      [entrypoints.http.transport.lifeCycle]
        requestAcceptGraceTimeout = "60s"
        graceTimeOut = "60s"
      [entrypoints.http.transport.respondingTimeouts]
        readTimeout = "60s"
        writeTimeout = "60s"
        idleTimeout = "180s"
    [entrypoints.http.forwardedHeaders]
      insecure = true
  [entrypoints.https]
    Address = "xxxx"
    [entrypoints.https.transport]
      [entrypoints.https.transport.lifeCycle]
        requestAcceptGraceTimeout = "60s"
        graceTimeOut = "60s"
      [entrypoints.https.transport.respondingTimeouts]
        readTimeout = "60s"
        writeTimeout = "60s"
        idleTimeout = "180s"
    [entrypoints.https.forwardedHeaders]
      insecure = true
  [entrypoints.admin]
    Address = "xxxx"
    [entrypoints.admin.forwardedHeaders]
      insecure = true
  [entrypoints.traefik]
    address = "127.0.0.1:8086"
```

log info
```
{"level":"error","msg":"Error in Go routine: runtime error: invalid memory address or nil pointer dereference","time":"2020-03-26T19:39:07+08:00"}
{"level":"error","msg":"Stack: goroutine 101 [running]:\nruntime/debug.Stack(0xc00004c0e0, 0x24798ae, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x2050480, 0x3e81920)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:66 +0xb1\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x2555b58)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:56 +0x57\npanic(0x2050480, 0x3e81920)\n\t/usr/local/go/src/runtime/panic.go:967 +0x166\ngithub.com/containous/traefik/v2/pkg/metrics.(*prometheusState).ListenValueUpdates(0xc0002b53c0)\n\t/go/src/github.com/containous/traefik/pkg/metrics/prometheus.go:264 +0x9a\ngithub.com/containous/traefik/v2/pkg/metrics.initStandardRegistry.func1()\n\t/go/src/github.com/containous/traefik/pkg/metrics/prometheus.go:99 +0x2d\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x2555b58, 0x2555a08)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:59 +0x4f\ncreated by github.com/containous/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:53 +0x49\n","time":"2020-03-26T19:39:07+08:00"}
```
```
Error in Go routine: runtime error: invalid memory address or nil pointer dereference

Stack: goroutine 101 [running]:
runtime/debug.Stack(0xc00004c0e0, 0x24798ae, 0x17)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x2050480, 0x3e81920)
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:66 +0xb1
github.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x2555b58)
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:56 +0x57
panic(0x2050480, 0x3e81920)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/containous/traefik/v2/pkg/metrics.(*prometheusState).ListenValueUpdates(0xc0002b53c0)
	/go/src/github.com/containous/traefik/pkg/metrics/prometheus.go:264 +0x9a
github.com/containous/traefik/v2/pkg/metrics.initStandardRegistry.func1()
	/go/src/github.com/containous/traefik/pkg/metrics/prometheus.go:99 +0x2d
github.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x2555b58, 0x2555a08)
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:59 +0x4f
created by github.com/containous/traefik/v2/pkg/safe.GoWithRecover
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:53 +0x49
```

issue
 * traefik process can not stop  
 * Error in Go routine: runtime error: invalid memory address or nil pointer dereference

**Comment by ldez** [comment]
could you provide all your static configuration, thanks.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
