### ISSUE TITLE
100% CPU Load when creating an endless loop in service instead of error message

### ISSUE THREAD

**Issue by em0lar** [containous/traefik#6759]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I configured a HTTP service wrong (used the wrong port). My service URL was: {{ server_fqdn }}:443.

### What did you expect to see?
An error message which shows me that I created an endless loop.

### What did you see instead?
Traefik uses (nearly) 100% of my servers CPU

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.6
Codename:     cantal
Go version:   go1.13.8
Built:        2020-02-28T17:40:18Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
http:
  routers:
    dokuwiki_http:
      rule: "Host(`wiki.example.org`)"
      service: "dokuwiki-app@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    dokuwiki_https:
      rule: "Host(`wiki.example.org`)"
      service: "dokuwiki-app@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
  services:
    dokuwiki-app:
      loadBalancer:
        servers:
          - url: "http://example.org:443"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
goroutine 41432 [select]:
golang.org/x/net/http2.(*ClientConn).roundTrip(0xc043bbe780, 0xc043fe9200, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:1084 +0x9a0
golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc0000837a0, 0xc043fe9200, 0xc00a6b0e00, 0x705885, 0x1, 0xc0001dd560)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:447 +0x172
golang.org/x/net/http2.(*Transport).RoundTrip(...)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:408
golang.org/x/net/http2.noDialH2RoundTripper.RoundTrip(0xc0000837a0, 0xc043fe9200, 0xc0003a8ac0, 0x5, 0xc0001dd5f8)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:2589 +0x3e
net/http.(*Transport).roundTrip(0xc0000cfb80, 0xc043fe9200, 0x2027600, 0x1, 0xc043feab00)
	/usr/local/go/src/net/http/transport.go:485 +0xdc8
net/http.(*Transport).RoundTrip(0xc0000cfb80, 0xc043fe9200, 0x25694e3, 0xf, 0xc043feabe8)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc000711b80, 0x29c27a0, 0xc043f99770, 0xc043fe9100)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:249 +0x2a4
github.com/containous/traefik/v2/pkg/middlewares/pipelining.(*pipelining).ServeHTTP(0xc0000f5c60, 0x29d1e20, 0xc0438377b0, 0xc043fe9100)
	/go/src/github.com/containous/traefik/pkg/middlewares/pipelining/pipelining.go:36 +0xf0
github.com/containous/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0008bf580, 0x29d1e20, 0xc0438377b0, 0xc043fe9100)
	/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:29 +0x18d
github.com/vulcand/oxy/roundrobin.(*RoundRobin).ServeHTTP(0xc0004edb90, 0x29d1e20, 0xc0438377b0, 0xc043fe9000)
	/go/pkg/mod/github.com/vulcand/oxy@v1.0.0/roundrobin/rr.go:147 +0xfe
github.com/containous/traefik/v2/pkg/middlewares/emptybackendhandler.(*emptyBackend).ServeHTTP(0xc0000f5c90, 0x29d1e20, 0xc0438377b0, 0xc043fe9000)
	/go/src/github.com/containous/traefik/pkg/middlewares/emptybackendhandler/empty_backend_handler.go:31 +0x168
github.com/containous/traefik/v2/pkg/middlewares/tracing.(*forwarderMiddleware).ServeHTTP(0xc000787860, 0x29d1e20, 0xc0438377b0, 0xc043fe9000)
	/go/src/github.com/containous/traefik/pkg/middlewares/tracing/forwarder.go:38 +0x610
github.com/containous/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0008bf5c0, 0x29d1e20, 0xc0438377b0, 0xc043fe9000)
	/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:29 +0x18d
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000760720, 0x29d1e20, 0xc0438377b0, 0xc043fe9000)
	/go/pkg/mod/github.com/containous/mux@v0.0.0-20181024131434-c33f32e26898/mux.go:133 +0x104
github.com/containous/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0xc00077bf20, 0x29d1e20, 0xc0438377b0, 0xc043fe8e00)
	/go/src/github.com/containous/traefik/pkg/middlewares/recovery/recovery.go:33 +0x131
github.com/containous/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0007b0280, 0x29d1e20, 0xc0438377b0, 0xc043fe8e00)
	/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:29 +0x18d
github.com/containous/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc00000f968, 0x29d1e20, 0xc0438377b0, 0xc043fe8d00, 0xc042483c48)
	/go/src/github.com/containous/traefik/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x37d
github.com/containous/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1(0x29d1e20, 0xc0438377b0, 0xc043fe8d00)
	/go/src/github.com/containous/traefik/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x83
net/http.HandlerFunc.ServeHTTP(0xc00077bf80, 0x29d1e20, 0xc0438377b0, 0xc043fe8d00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/containous/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0xc00000f960, 0x29d1e20, 0xc0438377b0, 0xc043fe8d00)
	/go/src/github.com/containous/traefik/pkg/middlewares/handler_switcher.go:23 +0x70
github.com/containous/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc000387040, 0x29d1e20, 0xc0438377b0, 0xc043fe8d00)
	/go/src/github.com/containous/traefik/pkg/middlewares/forwardedheaders/forwarded_header.go:174 +0x10b
net/http.serverHandler.ServeHTTP(0xc000126460, 0x29d1e20, 0xc0438377b0, 0xc043fe8d00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x29db9e0, 0xc043b8fbf0, 0xc04350f180, 0xc000126460, 0x29d1e20, 0xc0438377b0, 0xc043fe8d00)
	/usr/local/go/src/net/http/server.go:3366 +0x8d
net/http.(*http2serverConn).runHandler(0xc043bbe480, 0xc0438377b0, 0xc043fe8d00, 0xc031320f60)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x9f
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5447 +0x4eb
```

**Comment by dtomcej** [comment]
Hello @em0lar,

Thank you for this report, unfortunately doing loop detection of this nature is out of scope of the Traefik project.

Traefik can do rudimentary loop detection on the routes that it creates internally, but in the case you have provided, it used external names and addresses to create the loop, and there is no really good way for us to determine if a loop has been created.

As soon as the request leaves Traefik and can be modified by another source, loop detection becomes infinitely harder, and does not really justify the extra overhead and processing required.

We are going to close this issue since Traefik itself does work properly, but we admit that there are configuration options that can cause issues, that may be unviable to fix. This is one of those cases.

If you have any further questions/concerns, please feel free to open an issue on our [community forum](https://community.containo.us/).

Thanks
