### ISSUE TITLE
Failing tests with Go 1.15

### ISSUE THREAD

**Issue by shibumi** [containous/traefik#7234]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried running the tests with Go 1.15 via `go test ./...

### What did you expect to see?

The tests should have succeeded

### What did you see instead?

```
FAIL	github.com/containous/traefik/v2/pkg/metrics [build failed]
?   	github.com/containous/traefik/v2/pkg/middlewares	[no test files]
ok  	github.com/containous/traefik/v2/pkg/middlewares/accesslog	0.300s
ok  	github.com/containous/traefik/v2/pkg/middlewares/addprefix	0.231s
--- FAIL: TestForwardAuthRemoveHopByHopHeaders (0.00s)
    forward_test.go:173:
        	Error Trace:	forward_test.go:173
        	Error:      	Not equal:
        	            	expected: 302
        	            	actual  : 500
        	Test:       	TestForwardAuthRemoveHopByHopHeaders
        	Messages:   	they should be equal
    forward_test.go:180:
        	Error Trace:	forward_test.go:180
        	Error:      	Received unexpected error:
        	            	http: no Location header in response
        	Test:       	TestForwardAuthRemoveHopByHopHeaders
        	Messages:   	there should be no error
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x558fd436a5ec]

goroutine 348 [running]:
testing.tRunner.func1.1(0x558fd46cb5e0, 0x558fd490e230)
	testing/testing.go:1057 +0x30d
testing.tRunner.func1(0xc00078f800)
	testing/testing.go:1060 +0x41a
panic(0x558fd46cb5e0, 0x558fd490e230)
	runtime/panic.go:969 +0x175
net/url.(*URL).String(0x0, 0xc00078f800, 0x558fd4738600)
	net/url/url.go:813 +0x4c
github.com/containous/traefik/v2/pkg/middlewares/auth.TestForwardAuthRemoveHopByHopHeaders(0xc00078f800)
	github.com/containous/traefik/v2/pkg/middlewares/auth/forward_test.go:181 +0x616
testing.tRunner(0xc00078f800, 0x558fd472ec00)
	testing/testing.go:1108 +0xef
created by testing.(*T).Run
	testing/testing.go:1159 +0x38d
FAIL	github.com/containous/traefik/v2/pkg/middlewares/auth	0.325s
```

Furthermore:
```
pkg/metrics/statsd_test.go:39:71: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/metrics/statsd_test.go:40:71: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/metrics/statsd_test.go:43:80: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/metrics/statsd_test.go:79:71: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/metrics/statsd_test.go:80:71: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/metrics/statsd_test.go:83:80: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.2.8

**Comment by ldez** [comment]
Hello,

- Traefik v2.2 uses go1.14.
- Traefik v2.3 uses go1.15.

We will not update Traefik v2.2 to go1.15 related to the impact of the changes of this Go version.

Related to #7169

Thanks anyway.
